$axure.loadCurrentPage({
  "url":"公司信息.html",
  "generationDate":new Date(1398670762982.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0bb5a053b18d41eda7eda080f01e4eb8",
    "type":"Axure:Page",
    "name":"公司信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"27de83e26d6a4472afbc8ce74c18d5a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":180,
              "y":172},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f63a06a53f6e423f9e48b52393e8030c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":180,
                  "y":172},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06ad4d21e36b4e3fada9ee501d3f30e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":163},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a637e7fb4743268ebc4338650e9e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":163},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"6c76f59829ac47b28acc9f638d53edd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":152,
              "y":130},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27a369870c443aaa04114d256ab44e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":152,
                  "y":130},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f54e1e680f84a51a3176928235e4e60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":178,
              "y":701},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a67b367e451c479c91b8185dce60b973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":178,
                  "y":701},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e04b00021d54bbf8cd6807e8c516c96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":687},
            "size":{
              "width":265,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c15a1a56da9f4595afcf99a9906ec56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":687},
                "size":{
                  "width":265,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u8.png"}},
{
          "id":"bae11e1a867a40529e5d5149d314189d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":735},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f54927ba1746f5997ba6c938f91cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":735},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"709c39b1ad4745e5858848543b3c4976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":204,
              "y":363},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c551c9faac46cfabf3c948536b4e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":204,
                  "y":363},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"601fec9b5efb409fb9e296a51f338630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":354},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d6a0163b244e22bede7f04df0cba30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":354},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"3dcbc8f8498d408da3af2a80f8b2c393",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":166,
              "y":511},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2836f752e049f6a442ebddccdb89b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":166,
                  "y":511},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17c5cea5041040328c440d2ac722cb90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":502},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7839f2d01b94045a5df9d63e5aadef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":502},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"992b503f536545419a138f0fbe075fde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":100,
              "y":555},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"befec3fe91334df4a2a86b304672dcf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":100,
                  "y":555},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"825e60cf30e54b11b9a0ce1204da6882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":546},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6745060634e34d658b75a16e0979db63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":546},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"781962e5c0a242318f58631feb62b279",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd324a1b9bed4a8280c12cfccc76ea81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"3cd2858963cc4fb4acdbdad3abd5fffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d70fe9f08f240f6a8cb981c415d56bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"597eb2bd93474bb3b73f4c6bace6a386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":152,
              "y":400},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e90169344e4c6f922a39a3b9bf45e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":152,
                  "y":400},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb107a10932451d94de6cf390153ea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":152,
              "y":597},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42953cc644814d63b0f058312fe2e026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":152,
                  "y":597},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17efd89a26f34e39be2004a8df485673",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":407,
              "y":473},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c3d81146a24d0580450c30ec66ede7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":473},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55d392cdb7f248c6b9a7719f15dc8fd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":400},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8b335a23ce748bba8900c5352a7a76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":400},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}},
{
          "id":"d5f69393139b4901bdab0106fe50235a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":407,
              "y":663},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5062f426a4e846bca253c44949855ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":663},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d14de09b9f0f416d840ef6a8a19ceb3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":590},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56cd48914dc74fdc87d470d46d1a9317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":590},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}},
{
          "id":"2d798429645748f38979dd705a3336a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":180,
              "y":216},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3936e3ed81164b50a704faa220641e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":180,
                  "y":216},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"401433892f3142439f1c00c78daa9e01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":207},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccff3e5c82334161b1d527691435cff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":207},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"00d2e557ab5343a78b08e73801a42ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":178,
              "y":787},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec976d292f1a4a968bf766ccf0261697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":178,
                  "y":787},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72033a977a1a4b21b63e1e1638b7c23e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":787},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651ca29a40174fc1931b732dd3e3c99f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":787},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"85bd6cd863d54d8abd8fd67174e735cb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":787},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74abc8a1b9fe4ae0b72f36b1f2e11f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":787},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"26a972d650714ff59106b5c3b76b5dd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":152,
              "y":834},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181a6d7d386f411dbd5d169e020044c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":152,
                  "y":834},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fd6821e55864b06bdac76bd9e9f9baa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":191,
              "y":877},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0c88dd46d2c484792e05de03b8440af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":191,
                  "y":877},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"482ae30da2aa4fcc95513a52b08d8c5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":868},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23fbde62e0f74a3baf52082b7a0c15f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":868},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"1a2bb65b2ae44be1a7efa13cbbaec474",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":178,
              "y":920},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f7451b0582476ca9ecb2001456afa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":178,
                  "y":920},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d182835e2f6449c9825799f275b304f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":911},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b643ce68bd74b0ba0c11559e6ac21bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":911},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"14f8530d302a47efa16d233c5512b45a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":178,
              "y":964},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea5469db9e040209f5d98b06a924a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":178,
                  "y":964},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b99651c8232144c99e94be816773bf47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":955},
            "size":{
              "width":139,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472d07822b214a03960155ba5a0f2ea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":955},
                "size":{
                  "width":139,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u47.png"}},
{
          "id":"87f7f8fb261e4afb8689f44ea566eb05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":126,
              "y":1007},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4742ec881a92401a872fe258bb138c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":126,
                  "y":1007},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4b5d7228fc4405191fc44a68e135ba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":258,
              "y":998},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08bc9bffbd2f4e58a6009df56598e55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":998},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"f67d046b70e6458db0d77a65098aa7b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":375,
              "y":967},
            "size":{
              "width":17,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"277c96a2667247a9a50b6ca0e1925fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":375,
                  "y":967},
                "size":{
                  "width":17,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u68.png"}},
{
          "id":"7d72fcf303b24768be37ce21bfd62aa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":258,
              "y":1042},
            "size":{
              "width":80,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddcb145e79d540208df7ef7290b743b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":258,
                  "y":1042},
                "size":{
                  "width":80,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u70.png"}},
{
          "id":"ee93e854213f45cdbbba78f19f78642d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":348,
              "y":1057},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a891cf8f199445bb8e1cbe8b8f645c4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":348,
                  "y":1057},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99c8943b9de84ee1a2271c6743d7442e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":158,
              "y":1094},
            "size":{
              "width":66,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aa37f72d06d445fb80a029aff5bb0a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":158,
                  "y":1094},
                "size":{
                  "width":66,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8355810d4f64033a8e9cbb013b38d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":183,
              "y":1137},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650b3fe1e6ae4cf6bf6333931068af73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":183,
                  "y":1137},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f07c5124791c46829c9f1c9b3438fac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":264,
              "y":1128},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"447afae5faaa4695a7172455c4dad0d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1128},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"e47c92023d9549a2b8abaef079e851b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":183,
              "y":1180},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b98dd19d7a49a8a8e5331c82be5231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":183,
                  "y":1180},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd79a2fd5cd74c598d555022963fe49b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":264,
              "y":1171},
            "size":{
              "width":139,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57a833c29641441abe8fa62770bc6783",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":1171},
                "size":{
                  "width":139,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u47.png"}},
{
          "id":"f6d75bfc82b44073b30a8cad38cab4d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":381,
              "y":1183},
            "size":{
              "width":17,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0b710490cb143e186a7f0f25f39b259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":381,
                  "y":1183},
                "size":{
                  "width":17,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u68.png"}},
{
          "id":"37229e4303b54102bb641850a4a2bfdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":264,
              "y":1215},
            "size":{
              "width":80,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da338f1c35c2471d9875f09a376e0a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":264,
                  "y":1215},
                "size":{
                  "width":80,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u70.png"}},
{
          "id":"cff0b3055e514f768c44d5ba5634e478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":354,
              "y":1230},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e5f9ca74974d7383607f70a4b60761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":354,
                  "y":1230},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"281c0fee747f4f049224ca0b761b10d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":167,
              "y":252},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7ad1c7d3b649b38a74209f033a4bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":167,
                  "y":252},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5be0cb30c1b64b94b82aef9354e435bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":409,
              "y":325},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c20a5b85f84a3bab70c91d5e925f55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":409,
                  "y":325},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23bae57180934d2ab193ae002d9019e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":252},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df43ad45533245f0b8c615795b3b7dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":252},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}},
{
          "id":"22f3b49811d04c59a1b50f24825214ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'新細明體-ExtB Regular', '新細明體-ExtB'",
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":550,
              "y":252},
            "size":{
              "width":330,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f01e8519b04f87bd37e86b6ebecfda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'新細明體-ExtB Regular', '新細明體-ExtB'",
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":252},
                "size":{
                  "width":330,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息/u96.png"}},
{
          "id":"63c5b13ef9c749e3a2d597038e8b8b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":264,
              "y":1270},
            "size":{
              "width":157,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97bbdc57f8ff430ca936c887d28e257c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":264,
                  "y":1270},
                "size":{
                  "width":157,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "27de83e26d6a4472afbc8ce74c18d5a5":{
      "scriptId":"u0"},
    "f63a06a53f6e423f9e48b52393e8030c":{
      "scriptId":"u1"},
    "06ad4d21e36b4e3fada9ee501d3f30e4":{
      "scriptId":"u2"},
    "b1a637e7fb4743268ebc4338650e9e05":{
      "scriptId":"u3"},
    "6c76f59829ac47b28acc9f638d53edd7":{
      "scriptId":"u4"},
    "f27a369870c443aaa04114d256ab44e0":{
      "scriptId":"u5"},
    "2f54e1e680f84a51a3176928235e4e60":{
      "scriptId":"u6"},
    "a67b367e451c479c91b8185dce60b973":{
      "scriptId":"u7"},
    "1e04b00021d54bbf8cd6807e8c516c96":{
      "scriptId":"u8"},
    "c15a1a56da9f4595afcf99a9906ec56d":{
      "scriptId":"u9"},
    "bae11e1a867a40529e5d5149d314189d":{
      "scriptId":"u10"},
    "f1f54927ba1746f5997ba6c938f91cc2":{
      "scriptId":"u11"},
    "709c39b1ad4745e5858848543b3c4976":{
      "scriptId":"u12"},
    "51c551c9faac46cfabf3c948536b4e30":{
      "scriptId":"u13"},
    "601fec9b5efb409fb9e296a51f338630":{
      "scriptId":"u14"},
    "20d6a0163b244e22bede7f04df0cba30":{
      "scriptId":"u15"},
    "3dcbc8f8498d408da3af2a80f8b2c393":{
      "scriptId":"u16"},
    "5c2836f752e049f6a442ebddccdb89b2":{
      "scriptId":"u17"},
    "17c5cea5041040328c440d2ac722cb90":{
      "scriptId":"u18"},
    "e7839f2d01b94045a5df9d63e5aadef6":{
      "scriptId":"u19"},
    "992b503f536545419a138f0fbe075fde":{
      "scriptId":"u20"},
    "befec3fe91334df4a2a86b304672dcf1":{
      "scriptId":"u21"},
    "825e60cf30e54b11b9a0ce1204da6882":{
      "scriptId":"u22"},
    "6745060634e34d658b75a16e0979db63":{
      "scriptId":"u23"},
    "781962e5c0a242318f58631feb62b279":{
      "scriptId":"u24"},
    "fd324a1b9bed4a8280c12cfccc76ea81":{
      "scriptId":"u25"},
    "3cd2858963cc4fb4acdbdad3abd5fffd":{
      "scriptId":"u26"},
    "2d70fe9f08f240f6a8cb981c415d56bd":{
      "scriptId":"u27"},
    "597eb2bd93474bb3b73f4c6bace6a386":{
      "scriptId":"u28"},
    "c3e90169344e4c6f922a39a3b9bf45e6":{
      "scriptId":"u29"},
    "4cb107a10932451d94de6cf390153ea9":{
      "scriptId":"u30"},
    "42953cc644814d63b0f058312fe2e026":{
      "scriptId":"u31"},
    "17efd89a26f34e39be2004a8df485673":{
      "scriptId":"u32"},
    "24c3d81146a24d0580450c30ec66ede7":{
      "scriptId":"u33"},
    "55d392cdb7f248c6b9a7719f15dc8fd9":{
      "scriptId":"u34"},
    "d8b335a23ce748bba8900c5352a7a76b":{
      "scriptId":"u35"},
    "d5f69393139b4901bdab0106fe50235a":{
      "scriptId":"u36"},
    "5062f426a4e846bca253c44949855ca9":{
      "scriptId":"u37"},
    "d14de09b9f0f416d840ef6a8a19ceb3b":{
      "scriptId":"u38"},
    "56cd48914dc74fdc87d470d46d1a9317":{
      "scriptId":"u39"},
    "2d798429645748f38979dd705a3336a4":{
      "scriptId":"u40"},
    "3936e3ed81164b50a704faa220641e01":{
      "scriptId":"u41"},
    "401433892f3142439f1c00c78daa9e01":{
      "scriptId":"u42"},
    "ccff3e5c82334161b1d527691435cff3":{
      "scriptId":"u43"},
    "00d2e557ab5343a78b08e73801a42ab1":{
      "scriptId":"u44"},
    "ec976d292f1a4a968bf766ccf0261697":{
      "scriptId":"u45"},
    "72033a977a1a4b21b63e1e1638b7c23e":{
      "scriptId":"u46"},
    "651ca29a40174fc1931b732dd3e3c99f":{
      "scriptId":"u47"},
    "85bd6cd863d54d8abd8fd67174e735cb":{
      "scriptId":"u48"},
    "74abc8a1b9fe4ae0b72f36b1f2e11f7f":{
      "scriptId":"u49"},
    "26a972d650714ff59106b5c3b76b5dd5":{
      "scriptId":"u50"},
    "181a6d7d386f411dbd5d169e020044c4":{
      "scriptId":"u51"},
    "8fd6821e55864b06bdac76bd9e9f9baa":{
      "scriptId":"u52"},
    "d0c88dd46d2c484792e05de03b8440af":{
      "scriptId":"u53"},
    "482ae30da2aa4fcc95513a52b08d8c5c":{
      "scriptId":"u54"},
    "23fbde62e0f74a3baf52082b7a0c15f5":{
      "scriptId":"u55"},
    "1a2bb65b2ae44be1a7efa13cbbaec474":{
      "scriptId":"u56"},
    "12f7451b0582476ca9ecb2001456afa6":{
      "scriptId":"u57"},
    "d182835e2f6449c9825799f275b304f6":{
      "scriptId":"u58"},
    "3b643ce68bd74b0ba0c11559e6ac21bd":{
      "scriptId":"u59"},
    "14f8530d302a47efa16d233c5512b45a":{
      "scriptId":"u60"},
    "bea5469db9e040209f5d98b06a924a6b":{
      "scriptId":"u61"},
    "b99651c8232144c99e94be816773bf47":{
      "scriptId":"u62"},
    "472d07822b214a03960155ba5a0f2ea9":{
      "scriptId":"u63"},
    "87f7f8fb261e4afb8689f44ea566eb05":{
      "scriptId":"u64"},
    "4742ec881a92401a872fe258bb138c75":{
      "scriptId":"u65"},
    "f4b5d7228fc4405191fc44a68e135ba6":{
      "scriptId":"u66"},
    "08bc9bffbd2f4e58a6009df56598e55e":{
      "scriptId":"u67"},
    "f67d046b70e6458db0d77a65098aa7b1":{
      "scriptId":"u68"},
    "277c96a2667247a9a50b6ca0e1925fef":{
      "scriptId":"u69"},
    "7d72fcf303b24768be37ce21bfd62aa2":{
      "scriptId":"u70"},
    "ddcb145e79d540208df7ef7290b743b5":{
      "scriptId":"u71"},
    "ee93e854213f45cdbbba78f19f78642d":{
      "scriptId":"u72"},
    "a891cf8f199445bb8e1cbe8b8f645c4e":{
      "scriptId":"u73"},
    "99c8943b9de84ee1a2271c6743d7442e":{
      "scriptId":"u74"},
    "4aa37f72d06d445fb80a029aff5bb0a9":{
      "scriptId":"u75"},
    "e8355810d4f64033a8e9cbb013b38d06":{
      "scriptId":"u76"},
    "650b3fe1e6ae4cf6bf6333931068af73":{
      "scriptId":"u77"},
    "f07c5124791c46829c9f1c9b3438fac7":{
      "scriptId":"u78"},
    "447afae5faaa4695a7172455c4dad0d5":{
      "scriptId":"u79"},
    "e47c92023d9549a2b8abaef079e851b8":{
      "scriptId":"u80"},
    "12b98dd19d7a49a8a8e5331c82be5231":{
      "scriptId":"u81"},
    "bd79a2fd5cd74c598d555022963fe49b":{
      "scriptId":"u82"},
    "57a833c29641441abe8fa62770bc6783":{
      "scriptId":"u83"},
    "f6d75bfc82b44073b30a8cad38cab4d5":{
      "scriptId":"u84"},
    "b0b710490cb143e186a7f0f25f39b259":{
      "scriptId":"u85"},
    "37229e4303b54102bb641850a4a2bfdb":{
      "scriptId":"u86"},
    "da338f1c35c2471d9875f09a376e0a5b":{
      "scriptId":"u87"},
    "cff0b3055e514f768c44d5ba5634e478":{
      "scriptId":"u88"},
    "91e5f9ca74974d7383607f70a4b60761":{
      "scriptId":"u89"},
    "281c0fee747f4f049224ca0b761b10d2":{
      "scriptId":"u90"},
    "5a7ad1c7d3b649b38a74209f033a4bfa":{
      "scriptId":"u91"},
    "5be0cb30c1b64b94b82aef9354e435bb":{
      "scriptId":"u92"},
    "85c20a5b85f84a3bab70c91d5e925f55":{
      "scriptId":"u93"},
    "23bae57180934d2ab193ae002d9019e3":{
      "scriptId":"u94"},
    "df43ad45533245f0b8c615795b3b7dba":{
      "scriptId":"u95"},
    "22f3b49811d04c59a1b50f24825214ae":{
      "scriptId":"u96"},
    "34f01e8519b04f87bd37e86b6ebecfda":{
      "scriptId":"u97"},
    "63c5b13ef9c749e3a2d597038e8b8b4a":{
      "scriptId":"u98"},
    "97bbdc57f8ff430ca936c887d28e257c":{
      "scriptId":"u99"}}});