$axure.loadCurrentPage({
  "url":"消息详情.html",
  "generationDate":new Date(1398670770971.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8860289dd576438da8bf0cd85ba0b976",
    "type":"Axure:Page",
    "name":"消息详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a9713b9bcd94a0389f5c31a7ccfa3f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":192},
            "size":{
              "width":720,
              "height":296},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7c98c58576545a1bb1f2d7986946ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":192},
                "size":{
                  "width":720,
                  "height":296},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息提醒/u0.png"}},
{
          "id":"cd7367e70e704cd9843900248b504014",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2755dffd79e24302b2d0369189358732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"cf30dfed41a04cd484e0a451678d8769",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6d719c61cc14c589bc18fbf625ae29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"4c19cea6848c4db5ab450f8a3464fe83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35109019e9314a71a1ec2d887a2a06e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ced42e8324cc4c23aae0abd0b8fdb09e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"663301022a854244ac36a322dd891c97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":254,
              "y":160},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56c654e07a484f79a17dfb9aa725c636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":254,
                  "y":160},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82b0fcacb994f48bdd0a19a381ffa79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":274,
              "y":211},
            "size":{
              "width":235,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c977b23501847bd923974e3226c1b92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":274,
                  "y":211},
                "size":{
                  "width":235,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"250181da6fbe4455b32a936b1739c877",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":237},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa1572eaf3ea46adbed84d462557da6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":237},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7780cda79b014a5592db74efd11c12f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":263},
            "size":{
              "width":159,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf37b13ae57491da8a3930abfd862a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":263},
                "size":{
                  "width":159,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac28e269824e4203962ceca82b874e96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":292},
            "size":{
              "width":632,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798f356635bb46aba54e40fcf5fcf9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":292},
                "size":{
                  "width":632,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"089510c032cc47f48a7cd90c89e0fb6c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":164}},
          "adaptiveStyles":{
},
          "masterId":"64ef5d695df945a48946f079fbf43263"},
{
          "id":"d2d8c70cfb184f49b3bc8009f5c046ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":44,
              "y":310},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84fdefc3fcd64f308dd28ad36aca74e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":44,
                  "y":310},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"433bf12a771c4623b1769b600bb53e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":103,
              "y":325},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97d93e5273884ca4b38411582e5b18b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":103,
                  "y":325},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e747e8c6dda241918cc9006ea771061f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":207,
              "y":325},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c51407895e714971a619a2b9017726f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":207,
                  "y":325},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"38c24755597c41aea1e613ed5334dad2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"77709b3fdca844528934a4389a804b6a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}},
    "64ef5d695df945a48946f079fbf43263":{
      "packageId":"64ef5d695df945a48946f079fbf43263",
      "type":"Axure:Master",
      "name":"个人中心导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"56d85a7253f04f199871d3fdaac67eb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":160},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54d0d231dc57413eb216e8a5475c9dd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":160},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端下载/u6.png"}},
{
            "id":"1e0f4221decc467292d7855ecad2942d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":176},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bafca570fd364993af282bb72432579d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":176},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bf065ea8e2524cb8a6fe5ddea7fa3ee7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":209},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9de695aac6647d9a7a33ed280804e6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":209},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"d301701ccc33484cb2242ca2c53f2383",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":224},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b18f011200514edcbb595a928a0179d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":224},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4934ead7da71400c9ab43b14f6a362fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":258},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9be11e8fe52842128120aadc8b74603a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":258},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"07a775e9b30c46caa300e984c7cf67e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":274},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b3dc8724bac4133ae5ee7395ca3ce67",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":274},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f5e3706d708b4504b18b68de0e7861c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b79941f04eb4e0c9d70b99d96a1443b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":307},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"ac020511ea4c4647b1bf97d34c91b1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":322},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15668114dd5d459f9801c82950ccd78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":322},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78594ff15dcc4f05a412c2b04ab0d489",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":356},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ca10fb183454aefb8b8ddc0e31f3c61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"4c20ee5a78e14909923e0d0fede69e51",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":372},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3193db17fc8c4d3da903e5d2c5aee2fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":372},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "77709b3fdca844528934a4389a804b6a":{
      "packageId":"77709b3fdca844528934a4389a804b6a",
      "type":"Axure:Master",
      "name":"页头 已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"436c35237f7a4192a9de61ade8b072e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a8c4e1678bf419e89e028089ad41092",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"55e4cec996fa4bd98d77d44827b62a86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce74cd922ea34d279d6d5bdc5f125d73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c65c9757d44d47a5b57c02491aa63dfc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":771,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"270ea7f3e5a7421aaf605bf2be76c814",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":771,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c857e624fe54b0ab532c11ad5bb5878",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":929,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93146bb689e494ea1e182df3b3964c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":929,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de94cc5f4864463881ef2d0cd4439c62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13e05c5e0b7c47aa985e3e286a62cfa2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cdd316832e441d4af9ee77d61b8d973",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":11},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f33c1284a649aa8edf3eb51f242296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":11},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8a9713b9bcd94a0389f5c31a7ccfa3f2":{
      "scriptId":"u0"},
    "d7c98c58576545a1bb1f2d7986946ca9":{
      "scriptId":"u1"},
    "cd7367e70e704cd9843900248b504014":{
      "scriptId":"u2"},
    "2755dffd79e24302b2d0369189358732":{
      "scriptId":"u3"},
    "cf30dfed41a04cd484e0a451678d8769":{
      "scriptId":"u4"},
    "f6d719c61cc14c589bc18fbf625ae29d":{
      "scriptId":"u5"},
    "4c19cea6848c4db5ab450f8a3464fe83":{
      "scriptId":"u6"},
    "35109019e9314a71a1ec2d887a2a06e9":{
      "scriptId":"u7"},
    "ced42e8324cc4c23aae0abd0b8fdb09e":{
      "scriptId":"u8",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u9"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u10"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u11"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u12"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u13"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u14"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u15"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u16"}},
    "663301022a854244ac36a322dd891c97":{
      "scriptId":"u17"},
    "56c654e07a484f79a17dfb9aa725c636":{
      "scriptId":"u18"},
    "d82b0fcacb994f48bdd0a19a381ffa79":{
      "scriptId":"u19"},
    "7c977b23501847bd923974e3226c1b92":{
      "scriptId":"u20"},
    "250181da6fbe4455b32a936b1739c877":{
      "scriptId":"u21"},
    "fa1572eaf3ea46adbed84d462557da6e":{
      "scriptId":"u22"},
    "7780cda79b014a5592db74efd11c12f2":{
      "scriptId":"u23"},
    "ebf37b13ae57491da8a3930abfd862a2":{
      "scriptId":"u24"},
    "ac28e269824e4203962ceca82b874e96":{
      "scriptId":"u25"},
    "798f356635bb46aba54e40fcf5fcf9da":{
      "scriptId":"u26"},
    "089510c032cc47f48a7cd90c89e0fb6c":{
      "scriptId":"u27",
      "56d85a7253f04f199871d3fdaac67eb6":{
        "scriptId":"u28"},
      "54d0d231dc57413eb216e8a5475c9dd0":{
        "scriptId":"u29"},
      "1e0f4221decc467292d7855ecad2942d":{
        "scriptId":"u30"},
      "bafca570fd364993af282bb72432579d":{
        "scriptId":"u31"},
      "bf065ea8e2524cb8a6fe5ddea7fa3ee7":{
        "scriptId":"u32"},
      "d9de695aac6647d9a7a33ed280804e6f":{
        "scriptId":"u33"},
      "d301701ccc33484cb2242ca2c53f2383":{
        "scriptId":"u34"},
      "b18f011200514edcbb595a928a0179d0":{
        "scriptId":"u35"},
      "4934ead7da71400c9ab43b14f6a362fa":{
        "scriptId":"u36"},
      "9be11e8fe52842128120aadc8b74603a":{
        "scriptId":"u37"},
      "07a775e9b30c46caa300e984c7cf67e2":{
        "scriptId":"u38"},
      "1b3dc8724bac4133ae5ee7395ca3ce67":{
        "scriptId":"u39"},
      "f5e3706d708b4504b18b68de0e7861c2":{
        "scriptId":"u40"},
      "2b79941f04eb4e0c9d70b99d96a1443b":{
        "scriptId":"u41"},
      "ac020511ea4c4647b1bf97d34c91b1e3":{
        "scriptId":"u42"},
      "15668114dd5d459f9801c82950ccd78d":{
        "scriptId":"u43"},
      "78594ff15dcc4f05a412c2b04ab0d489":{
        "scriptId":"u44"},
      "6ca10fb183454aefb8b8ddc0e31f3c61":{
        "scriptId":"u45"},
      "4c20ee5a78e14909923e0d0fede69e51":{
        "scriptId":"u46"},
      "3193db17fc8c4d3da903e5d2c5aee2fd":{
        "scriptId":"u47"}},
    "d2d8c70cfb184f49b3bc8009f5c046ce":{
      "scriptId":"u48"},
    "84fdefc3fcd64f308dd28ad36aca74e6":{
      "scriptId":"u49"},
    "433bf12a771c4623b1769b600bb53e0a":{
      "scriptId":"u50"},
    "97d93e5273884ca4b38411582e5b18b4":{
      "scriptId":"u51"},
    "e747e8c6dda241918cc9006ea771061f":{
      "scriptId":"u52"},
    "c51407895e714971a619a2b9017726f3":{
      "scriptId":"u53"},
    "38c24755597c41aea1e613ed5334dad2":{
      "scriptId":"u54",
      "436c35237f7a4192a9de61ade8b072e7":{
        "scriptId":"u55"},
      "0a8c4e1678bf419e89e028089ad41092":{
        "scriptId":"u56"},
      "55e4cec996fa4bd98d77d44827b62a86":{
        "scriptId":"u57"},
      "ce74cd922ea34d279d6d5bdc5f125d73":{
        "scriptId":"u58"},
      "c65c9757d44d47a5b57c02491aa63dfc":{
        "scriptId":"u59"},
      "270ea7f3e5a7421aaf605bf2be76c814":{
        "scriptId":"u60"},
      "8c857e624fe54b0ab532c11ad5bb5878":{
        "scriptId":"u61"},
      "c93146bb689e494ea1e182df3b3964c3":{
        "scriptId":"u62"},
      "de94cc5f4864463881ef2d0cd4439c62":{
        "scriptId":"u63"},
      "13e05c5e0b7c47aa985e3e286a62cfa2":{
        "scriptId":"u64"},
      "9cdd316832e441d4af9ee77d61b8d973":{
        "scriptId":"u65"},
      "67f33c1284a649aa8edf3eb51f242296":{
        "scriptId":"u66"}}}});