$axure.loadCurrentPage({
  "url":"账号管理.html",
  "generationDate":new Date(1398670771765.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04972fc2870d411b99190e88036488a0",
    "type":"Axure:Page",
    "name":"账号管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d6def493dbba47c8959f929fa6b51403",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":95,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121df9a719524f55be44565f5c00fa70",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":64,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e24f680f2d954a25b186d9ee6d21eeaf",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":64,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ca4cc81f8854d93b2a0df368a3684a1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":64,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"61c3577d43714b5f98f28d155a7db28b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":75,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbe83a9f4abf4a6a907cadbe4cae2311",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":75,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0564c16222b6491ba8d4ccf5c5d8f2a6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":75,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"fbe83a9f4abf4a6a907cadbe4cae2311"},
{
                  "id":"00118883642d45a9b3df86f3eec13287",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1494b6b82e2745699faf0394b9c87f82",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/账号管理/u2.png",
                    "selected~":"images/账号管理/u2_selected.png"}},
{
                  "id":"3edb05b65fc241b1bd6d8fbb4e36c8bd",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":75,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d47a26a93cec4c8cb2fc7d4717f152d5",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":75,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8535795be2a34f778ece4e0b5a1b6c72",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":75,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"d47a26a93cec4c8cb2fc7d4717f152d5"},
{
                  "id":"8aabde5fed394acd8f60de21ac0ad1b5",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":75,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b97aaa58504142e6af188dca6a0b4548",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":75,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"193be40fc3d94b9d83693157227bc1c7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":75,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"b97aaa58504142e6af188dca6a0b4548"}],
              "buttonShapeId":"e24f680f2d954a25b186d9ee6d21eeaf"}]},
{
          "id":"2aada59dcdf34d44b4ab7ed5f283d8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":1000,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4accd45b6bf940d881794013b8c21137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":1000,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号管理/u15.png"}},
{
          "id":"d35802803c574dfd9a352fbc8ab851f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":26},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f1679508884bda93ab7dc48d71acc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":26},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"591446555e894cbd95a66e2cc46dee1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":705,
              "y":32},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a4bd9a3ffe41b78981faa9374b9c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":705,
                  "y":32},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce3ae670e3e54f87911e594a0cac158a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":923,
              "y":32},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74d133adaf9d49f580aa627488627557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":923,
                  "y":32},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd34a756291a4bed834a8caadc218415",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":32},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda86f03d2de47819c81781439d11bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":32},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d6def493dbba47c8959f929fa6b51403":{
      "scriptId":"u0"},
    "121df9a719524f55be44565f5c00fa70":{
      "scriptId":"u1"},
    "00118883642d45a9b3df86f3eec13287":{
      "scriptId":"u2"},
    "1494b6b82e2745699faf0394b9c87f82":{
      "scriptId":"u3"},
    "e24f680f2d954a25b186d9ee6d21eeaf":{
      "scriptId":"u4"},
    "1ca4cc81f8854d93b2a0df368a3684a1":{
      "scriptId":"u5"},
    "61c3577d43714b5f98f28d155a7db28b":{
      "scriptId":"u6"},
    "fbe83a9f4abf4a6a907cadbe4cae2311":{
      "scriptId":"u7"},
    "0564c16222b6491ba8d4ccf5c5d8f2a6":{
      "scriptId":"u8"},
    "3edb05b65fc241b1bd6d8fbb4e36c8bd":{
      "scriptId":"u9"},
    "d47a26a93cec4c8cb2fc7d4717f152d5":{
      "scriptId":"u10"},
    "8535795be2a34f778ece4e0b5a1b6c72":{
      "scriptId":"u11"},
    "8aabde5fed394acd8f60de21ac0ad1b5":{
      "scriptId":"u12"},
    "b97aaa58504142e6af188dca6a0b4548":{
      "scriptId":"u13"},
    "193be40fc3d94b9d83693157227bc1c7":{
      "scriptId":"u14"},
    "2aada59dcdf34d44b4ab7ed5f283d8f5":{
      "scriptId":"u15"},
    "4accd45b6bf940d881794013b8c21137":{
      "scriptId":"u16"},
    "d35802803c574dfd9a352fbc8ab851f1":{
      "scriptId":"u17"},
    "d7f1679508884bda93ab7dc48d71acc7":{
      "scriptId":"u18"},
    "591446555e894cbd95a66e2cc46dee1c":{
      "scriptId":"u19"},
    "10a4bd9a3ffe41b78981faa9374b9c55":{
      "scriptId":"u20"},
    "ce3ae670e3e54f87911e594a0cac158a":{
      "scriptId":"u21"},
    "74d133adaf9d49f580aa627488627557":{
      "scriptId":"u22"},
    "dd34a756291a4bed834a8caadc218415":{
      "scriptId":"u23"},
    "fda86f03d2de47819c81781439d11bfb":{
      "scriptId":"u24"}}});