$axure.loadCurrentPage({
  "url":"详情页_客户端_可编辑.html",
  "generationDate":new Date(1398670768296.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"941402ed3b5f49f8b17bbc5fcbe77f8e",
    "type":"Axure:Page",
    "name":"详情页 客户端 可编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cd270a9891cf45de925f586c39f54b26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"785b4ec831a64c4da26f4f6248e685be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"e9766c84ebbf46d284db69bf80b32d98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59a3dbf2e194c72b04716517c021387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"20b5b91033664148a31b6398de31b0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":215,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5174dfda633457687141a84124ca735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":215,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81f5279f56e456084dbdc45039f5303",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":160},
            "size":{
              "width":750,
              "height":562},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12cda8957cae459ab8d5acbade7ceed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":160},
                "size":{
                  "width":750,
                  "height":562},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/广告收益_酬金明细/u14.png"}},
{
          "id":"b7cd502291d741eb8925fcc89b894bbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":209},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29bfe222168047588f90980ecc2803e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":209},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0605b5fc40284f47876f2fc4c5a02d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":374,
              "y":209},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be4c56e19ddf4446be999430747df82e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":374,
                  "y":209},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ff9703b25c045ffbc3b9f74fce772e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":236},
            "size":{
              "width":617,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be7f5a135bd4fe8b81f6fd190f4944a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":236},
                "size":{
                  "width":617,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"831564d5279a4779bca28817b423205e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":263},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e44c0efaef46c6b8b001b1ea0f648d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":263},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24415c4e9e85456c9d8ecd779a6e299a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":300},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b6c15124b347279e255ce603d4d674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":300},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"776c1d22a963410ab560c2542c03267d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":182},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21208ceb6e614bf491b692d82caa3116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":182},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16d8ace49ee43b5955dd33fdd6533e7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":331},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235ac7973c8047ccac4dbe853ff18942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":331},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"65ced4c1fdcf43b5befa41dc22c6218f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":355},
            "size":{
              "width":211,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f8b5196ad96446cbb091cc5476cd1ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":355},
                "size":{
                  "width":211,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b99d65a312884f138c66fa297e7b6c03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":405},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd211723057e4239b06a4a09882ba4a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":405},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ebdfd23bf1548668692af94ee1e8647",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":405},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e64998a5cee4e0991e6a5a8ebfd194c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":405},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"48205574ab644467867e52d3faeafb0a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":405},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee0f609ada6419898c800a35b7cd6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":405},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9f8dd8028cc643a390428b30acb247bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":434},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a9150aff944700bdba41cdc71011ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":434},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a5d464ffc4c4ad0b748e74b80fed274",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":430},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbc352e98ed8423c8e98572177630aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":430},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"69f30de8e42c486e8af8b8ffd5287eb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":430},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0702932afb4ee98b0cca739f59099f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":430},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"575ec69b7b714b4ab27ab03b62eca317",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":557,
              "y":434},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc50fc3bef14420a0fbd4281a9df3ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":557,
                  "y":434},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df2e068f8b46431ca91fb6bcdaf3e89e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":430},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf7e5b97c2f4700940f1b1b78261e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":638,
                  "y":430},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"a2905dce05b846d3b2aa673c79053a60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":430},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd0a5c6e2f34afab902b8f452a9c09f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":430},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"d0b41900e04e4a0fa848655f3252e2c9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":464},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c5991f5726145ec9e627b3958ec3f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":464},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"96a55cb321ad449b884a3e2c05cdd56a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":491},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350fcb6d46354fa783c540078abccc22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":491},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"29090e6e65ee486b8a15ee0ccdb799e3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":491},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4723d8f42d6a483a97c4b203534246d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":491},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b2061deaa920417b944ee58f6dc0471c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef219c4b039447c8151445c188d18ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e69bd5f2dcdb48edb56a205e92d0aa87",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d344b455511477191b9bb1887ae2d83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"22ce500fb814481abf4aa292fe03414f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3fc726fb5c4b4fac183b81ce37ba95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"53af162ac4454e989d030df496555469",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":371,
              "y":570},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a926d149ed845a8b626f5d93d5fa330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":371,
                  "y":570},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"21a977c0ea35477ea156e1a33e7dec68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":649},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c21dd56fc6a46e3bb61997c9dc17f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":649},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"950b5a3c22f64f419856d6db6f5dd553",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":371,
              "y":664},
            "size":{
              "width":125,
              "height":125},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c93f539347249d692fad4b81ab89876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":371,
                  "y":664},
                "size":{
                  "width":125,
                  "height":125},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u76.png"}},
{
          "id":"9af6b1adbc254bd5b25d0bd6fd2e0ca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":380,
              "y":799},
            "size":{
              "width":107,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac69b5902aa4e1ebbd622702c4dcfce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":380,
                  "y":799},
                "size":{
                  "width":107,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4060239b4b7a491eb1bf9313a589466a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":381},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457d690b6a024c03ae009fdb0670f520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":381},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f4d419f88da4d2cbe26eca23539db77",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d8230afd0045db900135c0b16c6f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"27165e5e9b65454c8a6d8da83e61b99a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eae11af2e3346878d3a14be2375732d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fbc35c665abb4571b1d3e3ba8827c0f6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14fa754a924437589fdd125c609a80e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7eed3d8ed3e44fa1a79d4248ab63d613",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":371,
              "y":864},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f101f80442440ec8d7d9065ddb7c94a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":371,
                  "y":864},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"5a4176473f9549a9ae868d51a4a3ade9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"699eb4ec1bb34eba8187bf59f4df9a19",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":159}},
          "adaptiveStyles":{
},
          "masterId":"64ef5d695df945a48946f079fbf43263"},
{
          "id":"fcd3fc0a067b4b35980dca57a3836e42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":42,
              "y":209},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9316b77d0e84f88ac79a6f71a9b3b87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":42,
                  "y":209},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"e7736dc0603143229f0661fb5b1477fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":101,
              "y":224},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed4707c7ef54361b1d91360fe1c9bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":101,
                  "y":224},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9400bb8f6e634058a8fe645868cac87b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":205,
              "y":223},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e39c6d046264d96803c64166adff406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":205,
                  "y":223},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"e5a08c75b4624f43a2698569f8945be3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"77709b3fdca844528934a4389a804b6a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}},
    "64ef5d695df945a48946f079fbf43263":{
      "packageId":"64ef5d695df945a48946f079fbf43263",
      "type":"Axure:Master",
      "name":"个人中心导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"56d85a7253f04f199871d3fdaac67eb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":160},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54d0d231dc57413eb216e8a5475c9dd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":160},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端下载/u6.png"}},
{
            "id":"1e0f4221decc467292d7855ecad2942d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":176},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bafca570fd364993af282bb72432579d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":176},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bf065ea8e2524cb8a6fe5ddea7fa3ee7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":209},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9de695aac6647d9a7a33ed280804e6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":209},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"d301701ccc33484cb2242ca2c53f2383",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":224},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b18f011200514edcbb595a928a0179d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":224},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4934ead7da71400c9ab43b14f6a362fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":258},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9be11e8fe52842128120aadc8b74603a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":258},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"07a775e9b30c46caa300e984c7cf67e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":274},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b3dc8724bac4133ae5ee7395ca3ce67",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":274},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f5e3706d708b4504b18b68de0e7861c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b79941f04eb4e0c9d70b99d96a1443b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":307},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"ac020511ea4c4647b1bf97d34c91b1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":322},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15668114dd5d459f9801c82950ccd78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":322},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78594ff15dcc4f05a412c2b04ab0d489",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":356},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ca10fb183454aefb8b8ddc0e31f3c61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"4c20ee5a78e14909923e0d0fede69e51",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":372},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3193db17fc8c4d3da903e5d2c5aee2fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":372},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "77709b3fdca844528934a4389a804b6a":{
      "packageId":"77709b3fdca844528934a4389a804b6a",
      "type":"Axure:Master",
      "name":"页头 已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"436c35237f7a4192a9de61ade8b072e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a8c4e1678bf419e89e028089ad41092",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"55e4cec996fa4bd98d77d44827b62a86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce74cd922ea34d279d6d5bdc5f125d73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c65c9757d44d47a5b57c02491aa63dfc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":771,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"270ea7f3e5a7421aaf605bf2be76c814",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":771,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c857e624fe54b0ab532c11ad5bb5878",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":929,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93146bb689e494ea1e182df3b3964c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":929,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de94cc5f4864463881ef2d0cd4439c62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13e05c5e0b7c47aa985e3e286a62cfa2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cdd316832e441d4af9ee77d61b8d973",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":11},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f33c1284a649aa8edf3eb51f242296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":11},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "cd270a9891cf45de925f586c39f54b26":{
      "scriptId":"u0"},
    "785b4ec831a64c4da26f4f6248e685be":{
      "scriptId":"u1"},
    "e9766c84ebbf46d284db69bf80b32d98":{
      "scriptId":"u2"},
    "d59a3dbf2e194c72b04716517c021387":{
      "scriptId":"u3"},
    "20b5b91033664148a31b6398de31b0be":{
      "scriptId":"u4"},
    "f5174dfda633457687141a84124ca735":{
      "scriptId":"u5"},
    "f81f5279f56e456084dbdc45039f5303":{
      "scriptId":"u6"},
    "12cda8957cae459ab8d5acbade7ceed2":{
      "scriptId":"u7"},
    "b7cd502291d741eb8925fcc89b894bbe":{
      "scriptId":"u8"},
    "29bfe222168047588f90980ecc2803e1":{
      "scriptId":"u9"},
    "0605b5fc40284f47876f2fc4c5a02d38":{
      "scriptId":"u10"},
    "be4c56e19ddf4446be999430747df82e":{
      "scriptId":"u11"},
    "0ff9703b25c045ffbc3b9f74fce772e9":{
      "scriptId":"u12"},
    "0be7f5a135bd4fe8b81f6fd190f4944a":{
      "scriptId":"u13"},
    "831564d5279a4779bca28817b423205e":{
      "scriptId":"u14"},
    "01e44c0efaef46c6b8b001b1ea0f648d":{
      "scriptId":"u15"},
    "24415c4e9e85456c9d8ecd779a6e299a":{
      "scriptId":"u16"},
    "e2b6c15124b347279e255ce603d4d674":{
      "scriptId":"u17"},
    "776c1d22a963410ab560c2542c03267d":{
      "scriptId":"u18"},
    "21208ceb6e614bf491b692d82caa3116":{
      "scriptId":"u19"},
    "e16d8ace49ee43b5955dd33fdd6533e7":{
      "scriptId":"u20"},
    "235ac7973c8047ccac4dbe853ff18942":{
      "scriptId":"u21"},
    "65ced4c1fdcf43b5befa41dc22c6218f":{
      "scriptId":"u22"},
    "4f8b5196ad96446cbb091cc5476cd1ab":{
      "scriptId":"u23"},
    "b99d65a312884f138c66fa297e7b6c03":{
      "scriptId":"u24"},
    "bd211723057e4239b06a4a09882ba4a7":{
      "scriptId":"u25"},
    "5ebdfd23bf1548668692af94ee1e8647":{
      "scriptId":"u26"},
    "5e64998a5cee4e0991e6a5a8ebfd194c":{
      "scriptId":"u27"},
    "48205574ab644467867e52d3faeafb0a":{
      "scriptId":"u28"},
    "cee0f609ada6419898c800a35b7cd6e1":{
      "scriptId":"u29"},
    "9f8dd8028cc643a390428b30acb247bc":{
      "scriptId":"u30"},
    "07a9150aff944700bdba41cdc71011ed":{
      "scriptId":"u31"},
    "2a5d464ffc4c4ad0b748e74b80fed274":{
      "scriptId":"u32"},
    "dbc352e98ed8423c8e98572177630aba":{
      "scriptId":"u33"},
    "69f30de8e42c486e8af8b8ffd5287eb7":{
      "scriptId":"u34"},
    "bb0702932afb4ee98b0cca739f59099f":{
      "scriptId":"u35"},
    "575ec69b7b714b4ab27ab03b62eca317":{
      "scriptId":"u36"},
    "cdc50fc3bef14420a0fbd4281a9df3ec":{
      "scriptId":"u37"},
    "df2e068f8b46431ca91fb6bcdaf3e89e":{
      "scriptId":"u38"},
    "daf7e5b97c2f4700940f1b1b78261e00":{
      "scriptId":"u39"},
    "a2905dce05b846d3b2aa673c79053a60":{
      "scriptId":"u40"},
    "8dd0a5c6e2f34afab902b8f452a9c09f":{
      "scriptId":"u41"},
    "d0b41900e04e4a0fa848655f3252e2c9":{
      "scriptId":"u42"},
    "9c5991f5726145ec9e627b3958ec3f67":{
      "scriptId":"u43"},
    "96a55cb321ad449b884a3e2c05cdd56a":{
      "scriptId":"u44"},
    "350fcb6d46354fa783c540078abccc22":{
      "scriptId":"u45"},
    "29090e6e65ee486b8a15ee0ccdb799e3":{
      "scriptId":"u46"},
    "4723d8f42d6a483a97c4b203534246d6":{
      "scriptId":"u47"},
    "b2061deaa920417b944ee58f6dc0471c":{
      "scriptId":"u48"},
    "8ef219c4b039447c8151445c188d18ef":{
      "scriptId":"u49"},
    "e69bd5f2dcdb48edb56a205e92d0aa87":{
      "scriptId":"u50"},
    "4d344b455511477191b9bb1887ae2d83":{
      "scriptId":"u51"},
    "22ce500fb814481abf4aa292fe03414f":{
      "scriptId":"u52"},
    "3e3fc726fb5c4b4fac183b81ce37ba95":{
      "scriptId":"u53"},
    "53af162ac4454e989d030df496555469":{
      "scriptId":"u54"},
    "8a926d149ed845a8b626f5d93d5fa330":{
      "scriptId":"u55"},
    "21a977c0ea35477ea156e1a33e7dec68":{
      "scriptId":"u56"},
    "2c21dd56fc6a46e3bb61997c9dc17f70":{
      "scriptId":"u57"},
    "950b5a3c22f64f419856d6db6f5dd553":{
      "scriptId":"u58"},
    "6c93f539347249d692fad4b81ab89876":{
      "scriptId":"u59"},
    "9af6b1adbc254bd5b25d0bd6fd2e0ca0":{
      "scriptId":"u60"},
    "4ac69b5902aa4e1ebbd622702c4dcfce":{
      "scriptId":"u61"},
    "4060239b4b7a491eb1bf9313a589466a":{
      "scriptId":"u62"},
    "457d690b6a024c03ae009fdb0670f520":{
      "scriptId":"u63"},
    "9f4d419f88da4d2cbe26eca23539db77":{
      "scriptId":"u64"},
    "c1d8230afd0045db900135c0b16c6f39":{
      "scriptId":"u65"},
    "27165e5e9b65454c8a6d8da83e61b99a":{
      "scriptId":"u66"},
    "2eae11af2e3346878d3a14be2375732d":{
      "scriptId":"u67"},
    "fbc35c665abb4571b1d3e3ba8827c0f6":{
      "scriptId":"u68"},
    "b14fa754a924437589fdd125c609a80e":{
      "scriptId":"u69"},
    "7eed3d8ed3e44fa1a79d4248ab63d613":{
      "scriptId":"u70"},
    "6f101f80442440ec8d7d9065ddb7c94a":{
      "scriptId":"u71"},
    "5a4176473f9549a9ae868d51a4a3ade9":{
      "scriptId":"u72",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u73"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u74"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u75"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u76"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u77"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u78"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u79"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u80"}},
    "699eb4ec1bb34eba8187bf59f4df9a19":{
      "scriptId":"u81",
      "56d85a7253f04f199871d3fdaac67eb6":{
        "scriptId":"u82"},
      "54d0d231dc57413eb216e8a5475c9dd0":{
        "scriptId":"u83"},
      "1e0f4221decc467292d7855ecad2942d":{
        "scriptId":"u84"},
      "bafca570fd364993af282bb72432579d":{
        "scriptId":"u85"},
      "bf065ea8e2524cb8a6fe5ddea7fa3ee7":{
        "scriptId":"u86"},
      "d9de695aac6647d9a7a33ed280804e6f":{
        "scriptId":"u87"},
      "d301701ccc33484cb2242ca2c53f2383":{
        "scriptId":"u88"},
      "b18f011200514edcbb595a928a0179d0":{
        "scriptId":"u89"},
      "4934ead7da71400c9ab43b14f6a362fa":{
        "scriptId":"u90"},
      "9be11e8fe52842128120aadc8b74603a":{
        "scriptId":"u91"},
      "07a775e9b30c46caa300e984c7cf67e2":{
        "scriptId":"u92"},
      "1b3dc8724bac4133ae5ee7395ca3ce67":{
        "scriptId":"u93"},
      "f5e3706d708b4504b18b68de0e7861c2":{
        "scriptId":"u94"},
      "2b79941f04eb4e0c9d70b99d96a1443b":{
        "scriptId":"u95"},
      "ac020511ea4c4647b1bf97d34c91b1e3":{
        "scriptId":"u96"},
      "15668114dd5d459f9801c82950ccd78d":{
        "scriptId":"u97"},
      "78594ff15dcc4f05a412c2b04ab0d489":{
        "scriptId":"u98"},
      "6ca10fb183454aefb8b8ddc0e31f3c61":{
        "scriptId":"u99"},
      "4c20ee5a78e14909923e0d0fede69e51":{
        "scriptId":"u100"},
      "3193db17fc8c4d3da903e5d2c5aee2fd":{
        "scriptId":"u101"}},
    "fcd3fc0a067b4b35980dca57a3836e42":{
      "scriptId":"u102"},
    "c9316b77d0e84f88ac79a6f71a9b3b87":{
      "scriptId":"u103"},
    "e7736dc0603143229f0661fb5b1477fd":{
      "scriptId":"u104"},
    "7ed4707c7ef54361b1d91360fe1c9bce":{
      "scriptId":"u105"},
    "9400bb8f6e634058a8fe645868cac87b":{
      "scriptId":"u106"},
    "5e39c6d046264d96803c64166adff406":{
      "scriptId":"u107"},
    "e5a08c75b4624f43a2698569f8945be3":{
      "scriptId":"u108",
      "436c35237f7a4192a9de61ade8b072e7":{
        "scriptId":"u109"},
      "0a8c4e1678bf419e89e028089ad41092":{
        "scriptId":"u110"},
      "55e4cec996fa4bd98d77d44827b62a86":{
        "scriptId":"u111"},
      "ce74cd922ea34d279d6d5bdc5f125d73":{
        "scriptId":"u112"},
      "c65c9757d44d47a5b57c02491aa63dfc":{
        "scriptId":"u113"},
      "270ea7f3e5a7421aaf605bf2be76c814":{
        "scriptId":"u114"},
      "8c857e624fe54b0ab532c11ad5bb5878":{
        "scriptId":"u115"},
      "c93146bb689e494ea1e182df3b3964c3":{
        "scriptId":"u116"},
      "de94cc5f4864463881ef2d0cd4439c62":{
        "scriptId":"u117"},
      "13e05c5e0b7c47aa985e3e286a62cfa2":{
        "scriptId":"u118"},
      "9cdd316832e441d4af9ee77d61b8d973":{
        "scriptId":"u119"},
      "67f33c1284a649aa8edf3eb51f242296":{
        "scriptId":"u120"}}}});