$axure.loadCurrentPage({
  "url":"客户端下载.html",
  "generationDate":new Date(1398670764587.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f7c36b1b6311460d9794c529437706f2",
    "type":"Axure:Page",
    "name":"客户端下载",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9c981be92e024780be58d2ee3c43df3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03eb571a54454e8eac0db4cd574a44b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"50acfea9c478490f9af0a45afd329e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b8d52760e5457f8d1dc117fdcbc23e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"d515035e03ec46dfb3cf831e62fb44f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":160},
            "size":{
              "width":750,
              "height":980},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15e769faeb34607bdc2d745594fffd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":160},
                "size":{
                  "width":750,
                  "height":980},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u4.png"}},
{
          "id":"e27681b0c77541ebaf2f512b92e1a624",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f60f3743f7e148308b19804bc69a05b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u6.png"}},
{
          "id":"b51ea40b332c42e898f41d8d35846117",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":99,
              "y":176},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfb91b133c64b17b3f6c5395a5fe5df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":99,
                  "y":176},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25e99f7f161a44c18a08f43197c1af2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":209},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64bcd0c45ec40c090d60753bcf329d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":209},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u10.png"}},
{
          "id":"b0bc461afa6a4fe0a957dd70d95b30b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":99,
              "y":224},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24678579cce44777b6f2a83bf558c4ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":99,
                  "y":224},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf8ba5695663450ea44e9b03b9fd3391",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":40,
              "y":258},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4accef55802649fc83c4e8bd61bd5d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":40,
                  "y":258},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"2ffa3a7edbcc4b59ae5874286715ed25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":91,
              "y":274},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6493ac6c348413cb96eac97a5f52c1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":91,
                  "y":274},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3473fc0fb8c4ce3a0cde8babced1a49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":307},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b745466c1b014591b40505493ba56a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":307},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u10.png"}},
{
          "id":"6d90526d48e044579bc234fcbe92990c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":115,
              "y":322},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6653a0de5704315930f8be4b1ae27d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":115,
                  "y":322},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29722e1f85a84d62938f7a2a0cdbf524",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":203,
              "y":274},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc524b5270b24c33bbfff43c0107e386",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":203,
                  "y":274},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"6cbc6e4766644bb88affaab5ab8d3c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":209},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1129db5c3f4176810ce42130ae31d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":209},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67bacecb9b3641019db9a713dbaa75e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":374,
              "y":209},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87bbee2821d44187849b78ce5f15c118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":374,
                  "y":209},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4501526f5db47a58700551de433f2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":236},
            "size":{
              "width":617,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81bf08e08c1a4ae0917b5959685412ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":236},
                "size":{
                  "width":617,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8ac2ee72640461ca2cd702f1a6441a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":263},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e13f80456a4d6698656a63924cf65d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":263},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe5c698a09fd46b1b41d77cb71314d22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":300},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5faf816e2be340ad949eb038de22d78e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":300},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3659d1ef7f6a427eb97c74f20896435f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":182},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826639b851f640fcbfbdc96c74214d8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":182},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa86421be8d94611bd2cee47bee2898c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":331},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083d523a1f374a47add70f72139b5c73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":331},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1b0b300d4fc344499b16143f07ffb3fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":355},
            "size":{
              "width":211,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed8681c6ac343959047c28244b8b943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":355},
                "size":{
                  "width":211,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bc7f1d6605f40669237ef7518e822e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":405},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f0a331df3434e45ad651cbcf77eafaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":405},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc12fedda14449639a1fcbba656118ab",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":405},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce976d22e064583aa4056ae6ae6969f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":405},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7be66a28e07c4184911a738918e9dd6d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":405},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a04ff4a26de4f249fb5703e4f518da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":405},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb431721ea77499da4c458a5b024e190",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":434},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49c253fe1a3a4b9ea78290c52a2aed5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":434},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eac4252d737437c85c5f1041078f389",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":430},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cde0d8fab2e54ab5838703ab2781a564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":430},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"07d1f65226944287998f6ea5fc6b2259",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":430},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bcf4785f4e7414283599eece3dc40c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":430},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"a1bb7786f7d143b7b18d6145df51f0fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":557,
              "y":434},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0324969a6894381aa4484acb6b81689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":557,
                  "y":434},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e70d1a783e40d28efb6603fb56c700",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":430},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afc481ed87584c2dbff0c094065e004b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":638,
                  "y":430},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"933be46518414235b8229d852e3a363d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":430},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6c065b57f4a4c7ba6e76cf2e2f2d1e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":430},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"7ee07468aca244eda1cb7f7b6a919d9e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":464},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe8f4f76cb04de19f13133e7e98621c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":464},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4fafb953f406473a9dbc7274dca0ab47",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":491},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20f5f195a79471090a6ef73849bb8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":491},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb53e0c702a64b939a726df966f8acd5",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":491},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e481214ad28a454a9e60676807573942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":491},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ec3a082db3384b9ebc1abbc9c4f38b6c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c5dbe543e23427aa102f0e59f56a3c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3bad16171e364c0bb3b408b03f4cc491",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6691b2dbf8174dd0b4fffa05653c4bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"99a64cbf59fc4e608b836a9f125f4417",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":528},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"639e9bf5a7784c24af2086758101d9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":528},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"01219df0c55a489084257e9e40cfda6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":143,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50b7b110e1ec45d3852d6db82c95a8e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":143,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0503d90eb1084d59ab514dab04fb51eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":371,
              "y":570},
            "size":{
              "width":115,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fbeaca1bb4940eb90150dfffa8153be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":371,
                  "y":570},
                "size":{
                  "width":115,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u72.png"}},
{
          "id":"83359f60828c4c18a34de148ca213cf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":649},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b21c3eb96b4a95bf4858d890148073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":649},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c32a46310bf45b5b3eadbb467f57eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":371,
              "y":664},
            "size":{
              "width":125,
              "height":125},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eafca897dbd41e9a27fa4baee3279d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":371,
                  "y":664},
                "size":{
                  "width":125,
                  "height":125},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u76.png"}},
{
          "id":"785c04338d9f4d7d888a7cf02d93ab6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":380,
              "y":799},
            "size":{
              "width":107,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb411fe85e7e4789a9e34b5949bf92cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":380,
                  "y":799},
                "size":{
                  "width":107,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"636326f9236940ca941e208de8892e5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":319,
              "y":381},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97839158ade94e20873b902774ebd5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":319,
                  "y":381},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d88e76c3e8454e5590c00ca83c818ff3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"138984449e1940e4a5e68b174c93eab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8176cefbfdfe49a9b559984e383c6b28",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88760b28a04044ce950247404dbbe8f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e6707dd5f2454d8ea6fa50449ea82f75",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":381},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4efdc68e704487a9a190fea2aa0440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":381},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"550e5f001654416e960faa94fe8b627f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":371,
              "y":864},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76950c7a935144b6a82109aa9c2f81c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":371,
                  "y":864},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"fed77913f29f4671a265758562109050",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"b899dfc0369c44e49be22c0553918607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":495,
              "y":570},
            "size":{
              "width":115,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4bf55afc6ce4dbeae4c7b5256552372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":495,
                  "y":570},
                "size":{
                  "width":115,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u72.png"}},
{
          "id":"aeb0d371a0b348fca5792f7d64149f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":664},
            "size":{
              "width":125,
              "height":125},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be93ec701c3045899b44fc93c9751545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":664},
                "size":{
                  "width":125,
                  "height":125},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u76.png"}},
{
          "id":"8395e7b5529f4113b1f0c087fc0db0b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":709,
              "y":799},
            "size":{
              "width":107,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9889266708f9495183eaa2bd39497eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":709,
                  "y":799},
                "size":{
                  "width":107,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f139065d345948ef80c9ab90d3ac56a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":700,
              "y":864},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674b629814454f56a145972a935fc2cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":700,
                  "y":864},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}}},
  "objectPaths":{
    "9c981be92e024780be58d2ee3c43df3f":{
      "scriptId":"u0"},
    "03eb571a54454e8eac0db4cd574a44b8":{
      "scriptId":"u1"},
    "50acfea9c478490f9af0a45afd329e6a":{
      "scriptId":"u2"},
    "29b8d52760e5457f8d1dc117fdcbc23e":{
      "scriptId":"u3"},
    "d515035e03ec46dfb3cf831e62fb44f4":{
      "scriptId":"u4"},
    "d15e769faeb34607bdc2d745594fffd7":{
      "scriptId":"u5"},
    "e27681b0c77541ebaf2f512b92e1a624":{
      "scriptId":"u6"},
    "f60f3743f7e148308b19804bc69a05b0":{
      "scriptId":"u7"},
    "b51ea40b332c42e898f41d8d35846117":{
      "scriptId":"u8"},
    "5bfb91b133c64b17b3f6c5395a5fe5df":{
      "scriptId":"u9"},
    "25e99f7f161a44c18a08f43197c1af2c":{
      "scriptId":"u10"},
    "f64bcd0c45ec40c090d60753bcf329d4":{
      "scriptId":"u11"},
    "b0bc461afa6a4fe0a957dd70d95b30b3":{
      "scriptId":"u12"},
    "24678579cce44777b6f2a83bf558c4ff":{
      "scriptId":"u13"},
    "bf8ba5695663450ea44e9b03b9fd3391":{
      "scriptId":"u14"},
    "4accef55802649fc83c4e8bd61bd5d4d":{
      "scriptId":"u15"},
    "2ffa3a7edbcc4b59ae5874286715ed25":{
      "scriptId":"u16"},
    "d6493ac6c348413cb96eac97a5f52c1e":{
      "scriptId":"u17"},
    "e3473fc0fb8c4ce3a0cde8babced1a49":{
      "scriptId":"u18"},
    "b745466c1b014591b40505493ba56a97":{
      "scriptId":"u19"},
    "6d90526d48e044579bc234fcbe92990c":{
      "scriptId":"u20"},
    "e6653a0de5704315930f8be4b1ae27d2":{
      "scriptId":"u21"},
    "29722e1f85a84d62938f7a2a0cdbf524":{
      "scriptId":"u22"},
    "fc524b5270b24c33bbfff43c0107e386":{
      "scriptId":"u23"},
    "6cbc6e4766644bb88affaab5ab8d3c69":{
      "scriptId":"u24"},
    "4f1129db5c3f4176810ce42130ae31d9":{
      "scriptId":"u25"},
    "67bacecb9b3641019db9a713dbaa75e5":{
      "scriptId":"u26"},
    "87bbee2821d44187849b78ce5f15c118":{
      "scriptId":"u27"},
    "b4501526f5db47a58700551de433f2b3":{
      "scriptId":"u28"},
    "81bf08e08c1a4ae0917b5959685412ba":{
      "scriptId":"u29"},
    "c8ac2ee72640461ca2cd702f1a6441a5":{
      "scriptId":"u30"},
    "43e13f80456a4d6698656a63924cf65d":{
      "scriptId":"u31"},
    "fe5c698a09fd46b1b41d77cb71314d22":{
      "scriptId":"u32"},
    "5faf816e2be340ad949eb038de22d78e":{
      "scriptId":"u33"},
    "3659d1ef7f6a427eb97c74f20896435f":{
      "scriptId":"u34"},
    "826639b851f640fcbfbdc96c74214d8e":{
      "scriptId":"u35"},
    "aa86421be8d94611bd2cee47bee2898c":{
      "scriptId":"u36"},
    "083d523a1f374a47add70f72139b5c73":{
      "scriptId":"u37"},
    "1b0b300d4fc344499b16143f07ffb3fd":{
      "scriptId":"u38"},
    "eed8681c6ac343959047c28244b8b943":{
      "scriptId":"u39"},
    "3bc7f1d6605f40669237ef7518e822e7":{
      "scriptId":"u40"},
    "8f0a331df3434e45ad651cbcf77eafaf":{
      "scriptId":"u41"},
    "fc12fedda14449639a1fcbba656118ab":{
      "scriptId":"u42"},
    "8ce976d22e064583aa4056ae6ae6969f":{
      "scriptId":"u43"},
    "7be66a28e07c4184911a738918e9dd6d":{
      "scriptId":"u44"},
    "9a04ff4a26de4f249fb5703e4f518da4":{
      "scriptId":"u45"},
    "bb431721ea77499da4c458a5b024e190":{
      "scriptId":"u46"},
    "49c253fe1a3a4b9ea78290c52a2aed5b":{
      "scriptId":"u47"},
    "3eac4252d737437c85c5f1041078f389":{
      "scriptId":"u48"},
    "cde0d8fab2e54ab5838703ab2781a564":{
      "scriptId":"u49"},
    "07d1f65226944287998f6ea5fc6b2259":{
      "scriptId":"u50"},
    "3bcf4785f4e7414283599eece3dc40c8":{
      "scriptId":"u51"},
    "a1bb7786f7d143b7b18d6145df51f0fa":{
      "scriptId":"u52"},
    "a0324969a6894381aa4484acb6b81689":{
      "scriptId":"u53"},
    "e2e70d1a783e40d28efb6603fb56c700":{
      "scriptId":"u54"},
    "afc481ed87584c2dbff0c094065e004b":{
      "scriptId":"u55"},
    "933be46518414235b8229d852e3a363d":{
      "scriptId":"u56"},
    "a6c065b57f4a4c7ba6e76cf2e2f2d1e6":{
      "scriptId":"u57"},
    "7ee07468aca244eda1cb7f7b6a919d9e":{
      "scriptId":"u58"},
    "afe8f4f76cb04de19f13133e7e98621c":{
      "scriptId":"u59"},
    "4fafb953f406473a9dbc7274dca0ab47":{
      "scriptId":"u60"},
    "e20f5f195a79471090a6ef73849bb8b2":{
      "scriptId":"u61"},
    "bb53e0c702a64b939a726df966f8acd5":{
      "scriptId":"u62"},
    "e481214ad28a454a9e60676807573942":{
      "scriptId":"u63"},
    "ec3a082db3384b9ebc1abbc9c4f38b6c":{
      "scriptId":"u64"},
    "9c5dbe543e23427aa102f0e59f56a3c6":{
      "scriptId":"u65"},
    "3bad16171e364c0bb3b408b03f4cc491":{
      "scriptId":"u66"},
    "6691b2dbf8174dd0b4fffa05653c4bf9":{
      "scriptId":"u67"},
    "99a64cbf59fc4e608b836a9f125f4417":{
      "scriptId":"u68"},
    "639e9bf5a7784c24af2086758101d9d8":{
      "scriptId":"u69"},
    "01219df0c55a489084257e9e40cfda6e":{
      "scriptId":"u70"},
    "50b7b110e1ec45d3852d6db82c95a8e4":{
      "scriptId":"u71"},
    "0503d90eb1084d59ab514dab04fb51eb":{
      "scriptId":"u72"},
    "1fbeaca1bb4940eb90150dfffa8153be":{
      "scriptId":"u73"},
    "83359f60828c4c18a34de148ca213cf7":{
      "scriptId":"u74"},
    "32b21c3eb96b4a95bf4858d890148073":{
      "scriptId":"u75"},
    "1c32a46310bf45b5b3eadbb467f57eec":{
      "scriptId":"u76"},
    "7eafca897dbd41e9a27fa4baee3279d1":{
      "scriptId":"u77"},
    "785c04338d9f4d7d888a7cf02d93ab6c":{
      "scriptId":"u78"},
    "cb411fe85e7e4789a9e34b5949bf92cf":{
      "scriptId":"u79"},
    "636326f9236940ca941e208de8892e5e":{
      "scriptId":"u80"},
    "97839158ade94e20873b902774ebd5fd":{
      "scriptId":"u81"},
    "d88e76c3e8454e5590c00ca83c818ff3":{
      "scriptId":"u82"},
    "138984449e1940e4a5e68b174c93eab3":{
      "scriptId":"u83"},
    "8176cefbfdfe49a9b559984e383c6b28":{
      "scriptId":"u84"},
    "88760b28a04044ce950247404dbbe8f6":{
      "scriptId":"u85"},
    "e6707dd5f2454d8ea6fa50449ea82f75":{
      "scriptId":"u86"},
    "5c4efdc68e704487a9a190fea2aa0440":{
      "scriptId":"u87"},
    "550e5f001654416e960faa94fe8b627f":{
      "scriptId":"u88"},
    "76950c7a935144b6a82109aa9c2f81c5":{
      "scriptId":"u89"},
    "fed77913f29f4671a265758562109050":{
      "scriptId":"u90",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u91"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u92"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u93"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u94"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u95"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u96"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u97"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u98"}},
    "b899dfc0369c44e49be22c0553918607":{
      "scriptId":"u99"},
    "a4bf55afc6ce4dbeae4c7b5256552372":{
      "scriptId":"u100"},
    "aeb0d371a0b348fca5792f7d64149f84":{
      "scriptId":"u101"},
    "be93ec701c3045899b44fc93c9751545":{
      "scriptId":"u102"},
    "8395e7b5529f4113b1f0c087fc0db0b4":{
      "scriptId":"u103"},
    "9889266708f9495183eaa2bd39497eb4":{
      "scriptId":"u104"},
    "f139065d345948ef80c9ab90d3ac56a7":{
      "scriptId":"u105"},
    "674b629814454f56a145972a935fc2cb":{
      "scriptId":"u106"}}});