$axure.loadCurrentPage({
  "url":"提示_审核中.html",
  "generationDate":new Date(1398670763365.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"424fcc10c591469c82238acdedf34c01",
    "type":"Axure:Page",
    "name":"提示 审核中",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da13004afea54ff593680715484dd596",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b508ea81eb43fc978e5baf13fa93ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"dcf5ff916eee4fb099a379933f3c5525",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":55},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6624327086540729c4e84be9c6f5665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":55},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"c63c9f5001ab4e04bda04b6744fada24",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":118},
            "size":{
              "width":870,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提示_审核中/u4_line.png"}},
{
          "id":"ccac7378988d4c2384b316e8df8302e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":184},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2451f8c13e224e859d03a61b52dfeb3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":184},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f32309fad3446f8a7f4a11b911b5cda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":220},
            "size":{
              "width":400,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3504b4a2a0f84d09835431cfc3e37fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":220},
                "size":{
                  "width":400,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf9377034afa409fbd86274d2be19174",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":486,
              "y":246},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1095c820cea9474abb9ac38b725cf0c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":486,
                  "y":246},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da13004afea54ff593680715484dd596":{
      "scriptId":"u0"},
    "95b508ea81eb43fc978e5baf13fa93ed":{
      "scriptId":"u1"},
    "dcf5ff916eee4fb099a379933f3c5525":{
      "scriptId":"u2"},
    "a6624327086540729c4e84be9c6f5665":{
      "scriptId":"u3"},
    "c63c9f5001ab4e04bda04b6744fada24":{
      "scriptId":"u4"},
    "ccac7378988d4c2384b316e8df8302e7":{
      "scriptId":"u5"},
    "2451f8c13e224e859d03a61b52dfeb3c":{
      "scriptId":"u6"},
    "8f32309fad3446f8a7f4a11b911b5cda":{
      "scriptId":"u7"},
    "3504b4a2a0f84d09835431cfc3e37fcc":{
      "scriptId":"u8"},
    "cf9377034afa409fbd86274d2be19174":{
      "scriptId":"u9"},
    "1095c820cea9474abb9ac38b725cf0c5":{
      "scriptId":"u10"}}});