$axure.loadCurrentPage({
  "url":"详情页_宽带_不可编辑.html",
  "generationDate":new Date(1398670767770.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fd5e245a914a432c9b9aa4bad47537c9",
    "type":"Axure:Page",
    "name":"详情页 宽带 不可编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"43c3c3e49f6949acbb30510ace3ab5c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5066e567e950444a8d457a2cdd2688db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"b44d6fbf631d4c3b8e2b0a6f29dc8848",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f53c0ee96f9445ba9edc6a3f18991eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"cf312b5a5689497897036dbaa8fdd867",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":229,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbbfb8c0346f403d9156030f16d47c64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":229,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11de008341064faabbe45516d7610d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":160},
            "size":{
              "width":750,
              "height":1060},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e858df8c3941f892ff3dd2a984fbfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":160},
                "size":{
                  "width":750,
                  "height":1060},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页_宽带_不可编辑/u6.png"}},
{
          "id":"621a44596d294c0a86782b0aee952360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":293,
              "y":203},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e35de81c3ac45cbaec00402a6086c87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":293,
                  "y":203},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"717907e7412a4966bcf3c3df434f0c0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":365,
              "y":203},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f396bb50ade0450bbea8a64f7dc63632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":365,
                  "y":203},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e620dbeb65cb466cb9cb8d25dfc78483",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":293,
              "y":230},
            "size":{
              "width":617,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c1a06c53b34a23883f0fe3db1c6baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":293,
                  "y":230},
                "size":{
                  "width":617,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a95742eabd3e42139aff45cc2efd39e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":293,
              "y":257},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0975a4d680234914b185067f2eb3d61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":293,
                  "y":257},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7c05286a2c94f3c8ffb10728e56482d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":273,
              "y":314},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c690da152424aa1a8cee70d50dcc778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":273,
                  "y":314},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fab0e32acd3446092960b0132021e36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":273,
              "y":176},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84babd1ee1ab45578c9d093ed823a7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":273,
                  "y":176},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8c56588660045cfbe009e5303c6e84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":293,
              "y":283},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fab05b9758d049a6b1ebbc31f8fa423c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":293,
                  "y":283},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf9cd89d27594b97a37c27cbc9391a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":310,
              "y":364},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a67652c44df2412ba6c4e3779a789fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":310,
                  "y":364},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a53127f22fb4704b597f4205494a544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":310,
              "y":419},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fea225de02470282cbd53cab9ca6f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":310,
                  "y":419},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd7db2003de44de991f331c3d3398ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":310,
              "y":448},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80e3c5eaf604029a0fc32efb62bfd3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":310,
                  "y":448},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbe05b2cdca4486a847177a34bc46156",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":444},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fad516be75a4d8eb178b9cc8d88fbff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":444},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"b1d0d15dc66b404ba9d044cb45c11eda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":444},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2962a927db424ba6b8c82fb27db9002e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":444},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"8695dac0255f422ba3175899c4327db3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":548,
              "y":448},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0c93d4b473c42149266d3cbc00909d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":548,
                  "y":448},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b48a8d64b16543ff9ca0e2a23060945f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":444},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2054095193b94fd5a05f529682dd7fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":629,
                  "y":444},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"1df09b36c9d14f2f8ec3f30ae30dabef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":657,
              "y":444},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6051cf2c9e8e43b3bf17c6bf663a1a8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":657,
                  "y":444},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"157d8db5ba8049c1a3c80212eacd4c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":310,
              "y":392},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bb099fde0544b278ffa0f114a9ba101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":310,
                  "y":392},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54a8066001541afa8e81403478a366c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":293,
              "y":343},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732c11e4682a483cb3bd11747219c40f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":293,
                  "y":343},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ed274af3b7b47c0aaa33c6a20528ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":381,
              "y":392},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa2b13627bc44a38926a0a58c48727d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":381,
                  "y":392},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66afa11d56b74f2281147f8f18943e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":381,
              "y":418},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d30b848b456446ab7dd264d306dcfd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":381,
                  "y":418},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a612586256084aef93ff570eb3441af9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":293,
              "y":480},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d21999de424eafa88929e9865854c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":293,
                  "y":480},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c8c0dc1bfc847c783b2e932141e525a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":500},
            "size":{
              "width":200,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc20ba86860c4e70ab551dcf4b663e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":500},
                "size":{
                  "width":200,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u88.png"}},
{
          "id":"47280af5c7e94f238222c771356e3207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":518,
              "y":660},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d951a092a2384c53acce8ac8fab4f7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":518,
                  "y":660},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b05f0db0bda74941b69d8d9440f7beb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":710},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed68a400e364973ba7de0a19dd52687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":710},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"579898d804614f5ebdc548046a978049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":762},
            "size":{
              "width":590,
              "height":128},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069848a0b8464bc687a9a9dc1f90eeac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":762},
                "size":{
                  "width":590,
                  "height":128},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u94.png"}},
{
          "id":"e85156ff15b44ab186ea3374534ab503",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":736},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1208f40f802844a99dd7243eb08f8bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":736},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"254ca05ccc244862bc9084fd451b8f97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":910},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0cd00ff3d84335869fd9f3a3417273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":910},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a8a090014d34623b6b8461ab2f34639",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":936},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809363b0ae374dc2b3c0ba997c04977e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":936},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u102.png"}},
{
          "id":"7e760effe41c4114870f930ef00ba9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":320,
              "y":990},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a08e207219147f9a1b47d3eb7d86a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":320,
                  "y":990},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"39a6a2e24f894bea87528949040a7a3e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":393.5,
              "y":90}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"72ac7cfcfe014447ba0ac71198140bc5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":159}},
          "adaptiveStyles":{
},
          "masterId":"64ef5d695df945a48946f079fbf43263"},
{
          "id":"5468778fa6364590976a3389d129ae1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":42,
              "y":209},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12810f98b9534a8cb3867630d1f399ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":42,
                  "y":209},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"1258345d40394b559115175be344606a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":101,
              "y":224},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f3faed229e4a18baeda208d64a0dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":101,
                  "y":224},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cdd7ec1d13242aab051ef06bb3a2131",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":205,
              "y":223},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7781a021ebdf453d9778b31dd32942ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":205,
                  "y":223},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"70abb062ef9e47f1aefb076fe682adfd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"77709b3fdca844528934a4389a804b6a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}},
    "64ef5d695df945a48946f079fbf43263":{
      "packageId":"64ef5d695df945a48946f079fbf43263",
      "type":"Axure:Master",
      "name":"个人中心导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"56d85a7253f04f199871d3fdaac67eb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":160},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54d0d231dc57413eb216e8a5475c9dd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":160},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端下载/u6.png"}},
{
            "id":"1e0f4221decc467292d7855ecad2942d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":176},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bafca570fd364993af282bb72432579d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":176},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bf065ea8e2524cb8a6fe5ddea7fa3ee7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":209},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9de695aac6647d9a7a33ed280804e6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":209},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"d301701ccc33484cb2242ca2c53f2383",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":224},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b18f011200514edcbb595a928a0179d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":224},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4934ead7da71400c9ab43b14f6a362fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":258},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9be11e8fe52842128120aadc8b74603a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":258},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"07a775e9b30c46caa300e984c7cf67e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":274},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b3dc8724bac4133ae5ee7395ca3ce67",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":274},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f5e3706d708b4504b18b68de0e7861c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b79941f04eb4e0c9d70b99d96a1443b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":307},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"ac020511ea4c4647b1bf97d34c91b1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":322},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15668114dd5d459f9801c82950ccd78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":322},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78594ff15dcc4f05a412c2b04ab0d489",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":356},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ca10fb183454aefb8b8ddc0e31f3c61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"4c20ee5a78e14909923e0d0fede69e51",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":372},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3193db17fc8c4d3da903e5d2c5aee2fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":372},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "77709b3fdca844528934a4389a804b6a":{
      "packageId":"77709b3fdca844528934a4389a804b6a",
      "type":"Axure:Master",
      "name":"页头 已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"436c35237f7a4192a9de61ade8b072e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a8c4e1678bf419e89e028089ad41092",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"55e4cec996fa4bd98d77d44827b62a86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce74cd922ea34d279d6d5bdc5f125d73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c65c9757d44d47a5b57c02491aa63dfc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":771,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"270ea7f3e5a7421aaf605bf2be76c814",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":771,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c857e624fe54b0ab532c11ad5bb5878",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":929,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93146bb689e494ea1e182df3b3964c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":929,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de94cc5f4864463881ef2d0cd4439c62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13e05c5e0b7c47aa985e3e286a62cfa2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cdd316832e441d4af9ee77d61b8d973",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":11},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f33c1284a649aa8edf3eb51f242296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":11},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "43c3c3e49f6949acbb30510ace3ab5c0":{
      "scriptId":"u0"},
    "5066e567e950444a8d457a2cdd2688db":{
      "scriptId":"u1"},
    "b44d6fbf631d4c3b8e2b0a6f29dc8848":{
      "scriptId":"u2"},
    "f53c0ee96f9445ba9edc6a3f18991eff":{
      "scriptId":"u3"},
    "cf312b5a5689497897036dbaa8fdd867":{
      "scriptId":"u4"},
    "fbbfb8c0346f403d9156030f16d47c64":{
      "scriptId":"u5"},
    "11de008341064faabbe45516d7610d19":{
      "scriptId":"u6"},
    "a8e858df8c3941f892ff3dd2a984fbfd":{
      "scriptId":"u7"},
    "621a44596d294c0a86782b0aee952360":{
      "scriptId":"u8"},
    "6e35de81c3ac45cbaec00402a6086c87":{
      "scriptId":"u9"},
    "717907e7412a4966bcf3c3df434f0c0d":{
      "scriptId":"u10"},
    "f396bb50ade0450bbea8a64f7dc63632":{
      "scriptId":"u11"},
    "e620dbeb65cb466cb9cb8d25dfc78483":{
      "scriptId":"u12"},
    "71c1a06c53b34a23883f0fe3db1c6baa":{
      "scriptId":"u13"},
    "a95742eabd3e42139aff45cc2efd39e5":{
      "scriptId":"u14"},
    "0975a4d680234914b185067f2eb3d61f":{
      "scriptId":"u15"},
    "f7c05286a2c94f3c8ffb10728e56482d":{
      "scriptId":"u16"},
    "5c690da152424aa1a8cee70d50dcc778":{
      "scriptId":"u17"},
    "2fab0e32acd3446092960b0132021e36":{
      "scriptId":"u18"},
    "84babd1ee1ab45578c9d093ed823a7e5":{
      "scriptId":"u19"},
    "c8c56588660045cfbe009e5303c6e84c":{
      "scriptId":"u20"},
    "fab05b9758d049a6b1ebbc31f8fa423c":{
      "scriptId":"u21"},
    "bf9cd89d27594b97a37c27cbc9391a31":{
      "scriptId":"u22"},
    "a67652c44df2412ba6c4e3779a789fc1":{
      "scriptId":"u23"},
    "4a53127f22fb4704b597f4205494a544":{
      "scriptId":"u24"},
    "a4fea225de02470282cbd53cab9ca6f4":{
      "scriptId":"u25"},
    "bd7db2003de44de991f331c3d3398ee0":{
      "scriptId":"u26"},
    "f80e3c5eaf604029a0fc32efb62bfd3b":{
      "scriptId":"u27"},
    "fbe05b2cdca4486a847177a34bc46156":{
      "scriptId":"u28"},
    "0fad516be75a4d8eb178b9cc8d88fbff":{
      "scriptId":"u29"},
    "b1d0d15dc66b404ba9d044cb45c11eda":{
      "scriptId":"u30"},
    "2962a927db424ba6b8c82fb27db9002e":{
      "scriptId":"u31"},
    "8695dac0255f422ba3175899c4327db3":{
      "scriptId":"u32"},
    "d0c93d4b473c42149266d3cbc00909d0":{
      "scriptId":"u33"},
    "b48a8d64b16543ff9ca0e2a23060945f":{
      "scriptId":"u34"},
    "2054095193b94fd5a05f529682dd7fef":{
      "scriptId":"u35"},
    "1df09b36c9d14f2f8ec3f30ae30dabef":{
      "scriptId":"u36"},
    "6051cf2c9e8e43b3bf17c6bf663a1a8c":{
      "scriptId":"u37"},
    "157d8db5ba8049c1a3c80212eacd4c5d":{
      "scriptId":"u38"},
    "7bb099fde0544b278ffa0f114a9ba101":{
      "scriptId":"u39"},
    "e54a8066001541afa8e81403478a366c":{
      "scriptId":"u40"},
    "732c11e4682a483cb3bd11747219c40f":{
      "scriptId":"u41"},
    "7ed274af3b7b47c0aaa33c6a20528ec7":{
      "scriptId":"u42"},
    "aa2b13627bc44a38926a0a58c48727d9":{
      "scriptId":"u43"},
    "66afa11d56b74f2281147f8f18943e05":{
      "scriptId":"u44"},
    "9d30b848b456446ab7dd264d306dcfd0":{
      "scriptId":"u45"},
    "a612586256084aef93ff570eb3441af9":{
      "scriptId":"u46"},
    "96d21999de424eafa88929e9865854c0":{
      "scriptId":"u47"},
    "0c8c0dc1bfc847c783b2e932141e525a":{
      "scriptId":"u48"},
    "cc20ba86860c4e70ab551dcf4b663e28":{
      "scriptId":"u49"},
    "47280af5c7e94f238222c771356e3207":{
      "scriptId":"u50"},
    "d951a092a2384c53acce8ac8fab4f7f9":{
      "scriptId":"u51"},
    "b05f0db0bda74941b69d8d9440f7beb2":{
      "scriptId":"u52"},
    "1ed68a400e364973ba7de0a19dd52687":{
      "scriptId":"u53"},
    "579898d804614f5ebdc548046a978049":{
      "scriptId":"u54"},
    "069848a0b8464bc687a9a9dc1f90eeac":{
      "scriptId":"u55"},
    "e85156ff15b44ab186ea3374534ab503":{
      "scriptId":"u56"},
    "1208f40f802844a99dd7243eb08f8bff":{
      "scriptId":"u57"},
    "254ca05ccc244862bc9084fd451b8f97":{
      "scriptId":"u58"},
    "7b0cd00ff3d84335869fd9f3a3417273":{
      "scriptId":"u59"},
    "7a8a090014d34623b6b8461ab2f34639":{
      "scriptId":"u60"},
    "809363b0ae374dc2b3c0ba997c04977e":{
      "scriptId":"u61"},
    "7e760effe41c4114870f930ef00ba9d0":{
      "scriptId":"u62"},
    "6a08e207219147f9a1b47d3eb7d86a60":{
      "scriptId":"u63"},
    "39a6a2e24f894bea87528949040a7a3e":{
      "scriptId":"u64",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u65"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u66"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u67"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u68"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u69"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u70"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u71"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u72"}},
    "72ac7cfcfe014447ba0ac71198140bc5":{
      "scriptId":"u73",
      "56d85a7253f04f199871d3fdaac67eb6":{
        "scriptId":"u74"},
      "54d0d231dc57413eb216e8a5475c9dd0":{
        "scriptId":"u75"},
      "1e0f4221decc467292d7855ecad2942d":{
        "scriptId":"u76"},
      "bafca570fd364993af282bb72432579d":{
        "scriptId":"u77"},
      "bf065ea8e2524cb8a6fe5ddea7fa3ee7":{
        "scriptId":"u78"},
      "d9de695aac6647d9a7a33ed280804e6f":{
        "scriptId":"u79"},
      "d301701ccc33484cb2242ca2c53f2383":{
        "scriptId":"u80"},
      "b18f011200514edcbb595a928a0179d0":{
        "scriptId":"u81"},
      "4934ead7da71400c9ab43b14f6a362fa":{
        "scriptId":"u82"},
      "9be11e8fe52842128120aadc8b74603a":{
        "scriptId":"u83"},
      "07a775e9b30c46caa300e984c7cf67e2":{
        "scriptId":"u84"},
      "1b3dc8724bac4133ae5ee7395ca3ce67":{
        "scriptId":"u85"},
      "f5e3706d708b4504b18b68de0e7861c2":{
        "scriptId":"u86"},
      "2b79941f04eb4e0c9d70b99d96a1443b":{
        "scriptId":"u87"},
      "ac020511ea4c4647b1bf97d34c91b1e3":{
        "scriptId":"u88"},
      "15668114dd5d459f9801c82950ccd78d":{
        "scriptId":"u89"},
      "78594ff15dcc4f05a412c2b04ab0d489":{
        "scriptId":"u90"},
      "6ca10fb183454aefb8b8ddc0e31f3c61":{
        "scriptId":"u91"},
      "4c20ee5a78e14909923e0d0fede69e51":{
        "scriptId":"u92"},
      "3193db17fc8c4d3da903e5d2c5aee2fd":{
        "scriptId":"u93"}},
    "5468778fa6364590976a3389d129ae1b":{
      "scriptId":"u94"},
    "12810f98b9534a8cb3867630d1f399ac":{
      "scriptId":"u95"},
    "1258345d40394b559115175be344606a":{
      "scriptId":"u96"},
    "16f3faed229e4a18baeda208d64a0dbd":{
      "scriptId":"u97"},
    "5cdd7ec1d13242aab051ef06bb3a2131":{
      "scriptId":"u98"},
    "7781a021ebdf453d9778b31dd32942ed":{
      "scriptId":"u99"},
    "70abb062ef9e47f1aefb076fe682adfd":{
      "scriptId":"u100",
      "436c35237f7a4192a9de61ade8b072e7":{
        "scriptId":"u101"},
      "0a8c4e1678bf419e89e028089ad41092":{
        "scriptId":"u102"},
      "55e4cec996fa4bd98d77d44827b62a86":{
        "scriptId":"u103"},
      "ce74cd922ea34d279d6d5bdc5f125d73":{
        "scriptId":"u104"},
      "c65c9757d44d47a5b57c02491aa63dfc":{
        "scriptId":"u105"},
      "270ea7f3e5a7421aaf605bf2be76c814":{
        "scriptId":"u106"},
      "8c857e624fe54b0ab532c11ad5bb5878":{
        "scriptId":"u107"},
      "c93146bb689e494ea1e182df3b3964c3":{
        "scriptId":"u108"},
      "de94cc5f4864463881ef2d0cd4439c62":{
        "scriptId":"u109"},
      "13e05c5e0b7c47aa985e3e286a62cfa2":{
        "scriptId":"u110"},
      "9cdd316832e441d4af9ee77d61b8d973":{
        "scriptId":"u111"},
      "67f33c1284a649aa8edf3eb51f242296":{
        "scriptId":"u112"}}}});