$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1398670771386.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0894d97c78084703b2815b6f4eb2b3a1",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9d159b8518374beeac8a895e0ff9f71d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":192},
            "size":{
              "width":720,
              "height":296},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1319b95684b64d0281f48b10e37731c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":192},
                "size":{
                  "width":720,
                  "height":296},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息提醒/u0.png"}},
{
          "id":"61eb4d35482c4f2ea56b63460052b856",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cc36650f8e4f2b9cebdc224f420d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"548be3faae844be3aa0b83d5165f5728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a779347c374e4c40a050b6f98f81208e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"e0dcc5b5f86142ccbf26c2b3f198fea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4fb057a34ac401a847949c96f72e84a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3c9d38ad84148b6b008d95cb72d5fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":218},
            "size":{
              "width":208,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055a488fa3d24164b7a034b3b2a0dc9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":218},
                "size":{
                  "width":208,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u8.png"}},
{
          "id":"33a1435a59f049b9b7669189d963e38c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"000ade7ebe4949de8db2b73abf65df30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":254,
              "y":160},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ee1478577040aaabe0408fdedebfb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":254,
                  "y":160},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a5220fd23da431f89afded60dbaf799",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":228},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2141a2f03caf4e298e351fc05283720e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":228},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"793eef2438cb424786a4d633585157e7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":159}},
          "adaptiveStyles":{
},
          "masterId":"64ef5d695df945a48946f079fbf43263"},
{
          "id":"c6fb3eecaba14077b8e612cd6d23754e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":44,
              "y":355},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d1c9d5b58fb42ad83c4e7753b60ece8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":44,
                  "y":355},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"a0f9167afca5443988bfe51107eede02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":103,
              "y":370},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041bc90af2904b49811bcfcf395a2de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":103,
                  "y":370},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee9e3fa09aea433dba535cb4c49b53db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":207,
              "y":370},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72e9badb051d4a338cf6334a11d06d63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":207,
                  "y":370},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"e1498176e1844b86b015f74d823f3591",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":264},
            "size":{
              "width":208,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295b9f7bb826439eaf33c7b8272a2b48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":264},
                "size":{
                  "width":208,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u8.png"}},
{
          "id":"3b59d5c139e5483d8bd2552297e0eb30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":274},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a6c6a7ae24347c6b938a1e55dc0b671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":274},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7155cdba19e84634a0d180d902df741c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":364},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5729b223c12546a799f3050a2e26b63c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":364},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc96e83bed7e4909a982809756e0106f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":364},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11dfb22a985f46e2adc005aee6afd040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":364},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"421ab6f20f3c46dcb0680a51f92c0c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":310},
            "size":{
              "width":208,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70a6260afe3f4dc1b11959e1a421767e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":310},
                "size":{
                  "width":208,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u8.png"}},
{
          "id":"ad038b5a1af74f78afa2a71bccb00c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":320},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d1e7cada5e04b2d97fc773a3de0b0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":320},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9ec156cc48545609c5317631dd17176",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":393},
            "size":{
              "width":108,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59f24572c9904cfc90685a7aee778cb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":393},
                "size":{
                  "width":108,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u62.png"}},
{
          "id":"45bb95e29fb84e00be6cc89e75b6309c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":403},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44941a8ef1b74940828ee3b4fccc3a9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":403},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e17635c57bbf4dccab3311de13842163",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":393},
            "size":{
              "width":108,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0f9bd2b44e46c28f45e9ed1385dec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":393},
                "size":{
                  "width":108,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u62.png"}},
{
          "id":"c6053dddd2b948e3b8f2a0fe079e8b58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":372,
              "y":440},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532ba6dff5144f5e90f8129b11955706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":372,
                  "y":440},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"1101550618824956957a8d2795d2919b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"77709b3fdca844528934a4389a804b6a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}},
    "64ef5d695df945a48946f079fbf43263":{
      "packageId":"64ef5d695df945a48946f079fbf43263",
      "type":"Axure:Master",
      "name":"个人中心导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"56d85a7253f04f199871d3fdaac67eb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":160},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54d0d231dc57413eb216e8a5475c9dd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":160},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端下载/u6.png"}},
{
            "id":"1e0f4221decc467292d7855ecad2942d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":176},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bafca570fd364993af282bb72432579d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":176},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bf065ea8e2524cb8a6fe5ddea7fa3ee7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":209},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9de695aac6647d9a7a33ed280804e6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":209},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"d301701ccc33484cb2242ca2c53f2383",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":224},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b18f011200514edcbb595a928a0179d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":224},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4934ead7da71400c9ab43b14f6a362fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":258},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9be11e8fe52842128120aadc8b74603a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":258},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"07a775e9b30c46caa300e984c7cf67e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":274},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b3dc8724bac4133ae5ee7395ca3ce67",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":274},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f5e3706d708b4504b18b68de0e7861c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b79941f04eb4e0c9d70b99d96a1443b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":307},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"ac020511ea4c4647b1bf97d34c91b1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":322},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15668114dd5d459f9801c82950ccd78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":322},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78594ff15dcc4f05a412c2b04ab0d489",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":356},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ca10fb183454aefb8b8ddc0e31f3c61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"4c20ee5a78e14909923e0d0fede69e51",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":372},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3193db17fc8c4d3da903e5d2c5aee2fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":372},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "77709b3fdca844528934a4389a804b6a":{
      "packageId":"77709b3fdca844528934a4389a804b6a",
      "type":"Axure:Master",
      "name":"页头 已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"436c35237f7a4192a9de61ade8b072e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a8c4e1678bf419e89e028089ad41092",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"55e4cec996fa4bd98d77d44827b62a86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce74cd922ea34d279d6d5bdc5f125d73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c65c9757d44d47a5b57c02491aa63dfc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":771,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"270ea7f3e5a7421aaf605bf2be76c814",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":771,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c857e624fe54b0ab532c11ad5bb5878",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":929,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93146bb689e494ea1e182df3b3964c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":929,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de94cc5f4864463881ef2d0cd4439c62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13e05c5e0b7c47aa985e3e286a62cfa2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cdd316832e441d4af9ee77d61b8d973",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":11},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f33c1284a649aa8edf3eb51f242296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":11},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9d159b8518374beeac8a895e0ff9f71d":{
      "scriptId":"u0"},
    "1319b95684b64d0281f48b10e37731c0":{
      "scriptId":"u1"},
    "61eb4d35482c4f2ea56b63460052b856":{
      "scriptId":"u2"},
    "16cc36650f8e4f2b9cebdc224f420d0b":{
      "scriptId":"u3"},
    "548be3faae844be3aa0b83d5165f5728":{
      "scriptId":"u4"},
    "a779347c374e4c40a050b6f98f81208e":{
      "scriptId":"u5"},
    "e0dcc5b5f86142ccbf26c2b3f198fea0":{
      "scriptId":"u6"},
    "d4fb057a34ac401a847949c96f72e84a":{
      "scriptId":"u7"},
    "d3c9d38ad84148b6b008d95cb72d5fea":{
      "scriptId":"u8"},
    "055a488fa3d24164b7a034b3b2a0dc9e":{
      "scriptId":"u9"},
    "33a1435a59f049b9b7669189d963e38c":{
      "scriptId":"u10",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u11"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u12"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u13"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u14"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u15"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u16"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u17"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u18"}},
    "000ade7ebe4949de8db2b73abf65df30":{
      "scriptId":"u19"},
    "d5ee1478577040aaabe0408fdedebfb3":{
      "scriptId":"u20"},
    "2a5220fd23da431f89afded60dbaf799":{
      "scriptId":"u21"},
    "2141a2f03caf4e298e351fc05283720e":{
      "scriptId":"u22"},
    "793eef2438cb424786a4d633585157e7":{
      "scriptId":"u23",
      "56d85a7253f04f199871d3fdaac67eb6":{
        "scriptId":"u24"},
      "54d0d231dc57413eb216e8a5475c9dd0":{
        "scriptId":"u25"},
      "1e0f4221decc467292d7855ecad2942d":{
        "scriptId":"u26"},
      "bafca570fd364993af282bb72432579d":{
        "scriptId":"u27"},
      "bf065ea8e2524cb8a6fe5ddea7fa3ee7":{
        "scriptId":"u28"},
      "d9de695aac6647d9a7a33ed280804e6f":{
        "scriptId":"u29"},
      "d301701ccc33484cb2242ca2c53f2383":{
        "scriptId":"u30"},
      "b18f011200514edcbb595a928a0179d0":{
        "scriptId":"u31"},
      "4934ead7da71400c9ab43b14f6a362fa":{
        "scriptId":"u32"},
      "9be11e8fe52842128120aadc8b74603a":{
        "scriptId":"u33"},
      "07a775e9b30c46caa300e984c7cf67e2":{
        "scriptId":"u34"},
      "1b3dc8724bac4133ae5ee7395ca3ce67":{
        "scriptId":"u35"},
      "f5e3706d708b4504b18b68de0e7861c2":{
        "scriptId":"u36"},
      "2b79941f04eb4e0c9d70b99d96a1443b":{
        "scriptId":"u37"},
      "ac020511ea4c4647b1bf97d34c91b1e3":{
        "scriptId":"u38"},
      "15668114dd5d459f9801c82950ccd78d":{
        "scriptId":"u39"},
      "78594ff15dcc4f05a412c2b04ab0d489":{
        "scriptId":"u40"},
      "6ca10fb183454aefb8b8ddc0e31f3c61":{
        "scriptId":"u41"},
      "4c20ee5a78e14909923e0d0fede69e51":{
        "scriptId":"u42"},
      "3193db17fc8c4d3da903e5d2c5aee2fd":{
        "scriptId":"u43"}},
    "c6fb3eecaba14077b8e612cd6d23754e":{
      "scriptId":"u44"},
    "1d1c9d5b58fb42ad83c4e7753b60ece8":{
      "scriptId":"u45"},
    "a0f9167afca5443988bfe51107eede02":{
      "scriptId":"u46"},
    "041bc90af2904b49811bcfcf395a2de0":{
      "scriptId":"u47"},
    "ee9e3fa09aea433dba535cb4c49b53db":{
      "scriptId":"u48"},
    "72e9badb051d4a338cf6334a11d06d63":{
      "scriptId":"u49"},
    "e1498176e1844b86b015f74d823f3591":{
      "scriptId":"u50"},
    "295b9f7bb826439eaf33c7b8272a2b48":{
      "scriptId":"u51"},
    "3b59d5c139e5483d8bd2552297e0eb30":{
      "scriptId":"u52"},
    "5a6c6a7ae24347c6b938a1e55dc0b671":{
      "scriptId":"u53"},
    "7155cdba19e84634a0d180d902df741c":{
      "scriptId":"u54"},
    "5729b223c12546a799f3050a2e26b63c":{
      "scriptId":"u55"},
    "dc96e83bed7e4909a982809756e0106f":{
      "scriptId":"u56"},
    "11dfb22a985f46e2adc005aee6afd040":{
      "scriptId":"u57"},
    "421ab6f20f3c46dcb0680a51f92c0c95":{
      "scriptId":"u58"},
    "70a6260afe3f4dc1b11959e1a421767e":{
      "scriptId":"u59"},
    "ad038b5a1af74f78afa2a71bccb00c91":{
      "scriptId":"u60"},
    "4d1e7cada5e04b2d97fc773a3de0b0db":{
      "scriptId":"u61"},
    "a9ec156cc48545609c5317631dd17176":{
      "scriptId":"u62"},
    "59f24572c9904cfc90685a7aee778cb5":{
      "scriptId":"u63"},
    "45bb95e29fb84e00be6cc89e75b6309c":{
      "scriptId":"u64"},
    "44941a8ef1b74940828ee3b4fccc3a9c":{
      "scriptId":"u65"},
    "e17635c57bbf4dccab3311de13842163":{
      "scriptId":"u66"},
    "4f0f9bd2b44e46c28f45e9ed1385dec3":{
      "scriptId":"u67"},
    "c6053dddd2b948e3b8f2a0fe079e8b58":{
      "scriptId":"u68"},
    "532ba6dff5144f5e90f8129b11955706":{
      "scriptId":"u69"},
    "1101550618824956957a8d2795d2919b":{
      "scriptId":"u70",
      "436c35237f7a4192a9de61ade8b072e7":{
        "scriptId":"u71"},
      "0a8c4e1678bf419e89e028089ad41092":{
        "scriptId":"u72"},
      "55e4cec996fa4bd98d77d44827b62a86":{
        "scriptId":"u73"},
      "ce74cd922ea34d279d6d5bdc5f125d73":{
        "scriptId":"u74"},
      "c65c9757d44d47a5b57c02491aa63dfc":{
        "scriptId":"u75"},
      "270ea7f3e5a7421aaf605bf2be76c814":{
        "scriptId":"u76"},
      "8c857e624fe54b0ab532c11ad5bb5878":{
        "scriptId":"u77"},
      "c93146bb689e494ea1e182df3b3964c3":{
        "scriptId":"u78"},
      "de94cc5f4864463881ef2d0cd4439c62":{
        "scriptId":"u79"},
      "13e05c5e0b7c47aa985e3e286a62cfa2":{
        "scriptId":"u80"},
      "9cdd316832e441d4af9ee77d61b8d973":{
        "scriptId":"u81"},
      "67f33c1284a649aa8edf3eb51f242296":{
        "scriptId":"u82"}}}});