$axure.loadCurrentPage({
  "url":"公司信息_1.html",
  "generationDate":new Date(1398670770076.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94d7f69b0db34501bce15b5c863feb08",
    "type":"Axure:Page",
    "name":"公司信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89ab9973bd384ed88f7c755c5db53a11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fdfa22a9bef4e77b89da07fe19dd558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"3daf6f38e7bc48bc83ed4f5fa022e062",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22170b9662224fb99a464b6cb0c1db13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"b4fa64cb02034bbbab42088fec8459a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532270fd648a4e61a17009129ff92451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e81ef5ae9fae4c0f896b172f89255972",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":363,
              "y":160},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c37f51c42c3849ca9c4902dadf4dcd01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":363,
                  "y":160},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/广告收益_酬金明细/u10.png"}},
{
          "id":"5250c2edb1554df0bdc427b2b550ca3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":197},
            "size":{
              "width":750,
              "height":773},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b64dc20a5d2482cabccb62d29aec6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":197},
                "size":{
                  "width":750,
                  "height":773},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息_1/u8.png"}},
{
          "id":"2c54562f64544ca7962d1c311006d9a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":160},
            "size":{
              "width":100,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75ae685d516346f8b8e491d3e2d036ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":160},
                "size":{
                  "width":100,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司信息_1/u10.png"}},
{
          "id":"72bcdcf7c046431981d8e02be20c6e79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":374,
              "y":224},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c8660fd3a64fd3a32c53e35be360f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":374,
                  "y":224},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df17f19a7cd842c1924add873f58fabd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":398,
              "y":312},
            "size":{
              "width":31,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f88cf83d075402fa0d48e5a946c4ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":398,
                  "y":312},
                "size":{
                  "width":31,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"473209fb977d4157bf9b0fb1dce13445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":362,
              "y":356},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27263b5f53ee4c58932b47771211703d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":362,
                  "y":356},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"055d946f2978467ebfca0a787e2a9955",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":296,
              "y":400},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b8b69c9dce4a90945f57d4e91d11ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":296,
                  "y":400},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81cec878703b4cd68ff79cffb4993f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":374,
              "y":268},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ead1e6105ed742dfb3578aacefea2965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":374,
                  "y":268},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35902a82bb2d49748a8967ae58a9afcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":224},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca9f086ddec420e95d0ed703699cc97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":224},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cbfe134c75b4d24b08dace08b2dad43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":268},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93968030a744fb98a60189983bf96d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":268},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cd97e1ba07e4ea4966076cbdc37d798",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":312},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6600972b0a1648b28d8c69fe4162135c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":312},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"349704679fb74ee69c865b23be1ea86e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":356},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05a92b51c0bb4dc89ad7998d1c9aa6dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":356},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b15600b96cbf428db66a3effd1c820fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":400},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9882d7d437451e9b9abe0dd3047dbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":400},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e396db800f248479cdcf0ca2201cc06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":375,
              "y":442},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f1eb559bf74b208a77a5dc1f0890d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":375,
                  "y":442},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5284f425aa694de0aaaaa5c784696d3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":442},
            "size":{
              "width":36,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0fd2fd53bc4dc1841ba35d70bad7d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":442},
                "size":{
                  "width":36,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea9e153f746244ca9f1d97ab8710aea5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":379,
              "y":480},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd5918886094651805d6b498bd8ec46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":379,
                  "y":480},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"658a8400409f4fb1ae5585420e17d33b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":480},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e8a7e1a2494ded9c4218ff2a3e96df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":480},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da2af15b910c47ac9d72b70b125906c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "location":{
              "x":296,
              "y":530},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbba4069527c484998840ab038a98960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "location":{
                  "x":296,
                  "y":530},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91c5e33c319444f18414a11dcb1c58e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":388,
              "y":565},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5dfb47867904b569f0c72213185a819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":388,
                  "y":565},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"226694401e77422ca26ea2ccb7093a6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":376,
              "y":608},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"511e2ac0692041479d0a5308dfb98eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":376,
                  "y":608},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5812c99171c74340bbc2540db11fafaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":371,
              "y":652},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92f4a384c084b968f101fad8fe44d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":371,
                  "y":652},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8041d18a887e425eb73734ce2c5dc681",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":324,
              "y":695},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6abd5d6b31a40e19ce7c0c2eaaba35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":324,
                  "y":695},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"371499d5b7584d44a0ece8b24252df95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "location":{
              "x":295,
              "y":730},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5971543a9d394af6840ac58b2589e83c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "location":{
                  "x":295,
                  "y":730},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a099a57b84964a4f80ac5511078bbfe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":378,
              "y":765},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d19ab83367de4fabb2926d6aa987f974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":378,
                  "y":765},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb7e48f746dd4cb19b0570a380e58505",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":380,
              "y":808},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b10b75ed6e5a4101a04a79feb645084a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":380,
                  "y":808},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f63b529953d145ab8649ef4960c9dc65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":324,
              "y":854},
            "size":{
              "width":588,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984d48d8e12a405dabca027ef41da0f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":854},
                "size":{
                  "width":588,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ae8ba2df3e24f3fa4ebf2568971a1eb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"},
{
          "id":"a793ea91988f401e96fa84e8a03132ca",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":159}},
          "adaptiveStyles":{
},
          "masterId":"64ef5d695df945a48946f079fbf43263"},
{
          "id":"5fd0dc6e0e6941bcb43ae2d433d15540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":45,
              "y":257},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4774c4df22f746c9806db2ce2478b494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":45,
                  "y":257},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户端下载/u14.png"}},
{
          "id":"4620e1df096f488ba5ebd47ec1f0fea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":104,
              "y":273},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9792c3bbc8e9473bbe1c78104d45710c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":104,
                  "y":273},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6dd3b9cdce994c9eb99c28714b32dac4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":208,
              "y":273},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e122554b087745e4baeaf34e2dff01a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":208,
                  "y":273},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"683e48f9bf2f4cf2ab76f5c2ca4a25f5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"77709b3fdca844528934a4389a804b6a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}},
    "64ef5d695df945a48946f079fbf43263":{
      "packageId":"64ef5d695df945a48946f079fbf43263",
      "type":"Axure:Master",
      "name":"个人中心导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"56d85a7253f04f199871d3fdaac67eb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":160},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54d0d231dc57413eb216e8a5475c9dd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":160},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客户端下载/u6.png"}},
{
            "id":"1e0f4221decc467292d7855ecad2942d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":176},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bafca570fd364993af282bb72432579d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":176},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bf065ea8e2524cb8a6fe5ddea7fa3ee7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":209},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9de695aac6647d9a7a33ed280804e6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":209},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"d301701ccc33484cb2242ca2c53f2383",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":224},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b18f011200514edcbb595a928a0179d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":224},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4934ead7da71400c9ab43b14f6a362fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":258},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9be11e8fe52842128120aadc8b74603a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":258},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"07a775e9b30c46caa300e984c7cf67e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":274},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1b3dc8724bac4133ae5ee7395ca3ce67",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":274},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f5e3706d708b4504b18b68de0e7861c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":307},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b79941f04eb4e0c9d70b99d96a1443b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":307},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"ac020511ea4c4647b1bf97d34c91b1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":322},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15668114dd5d459f9801c82950ccd78d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":322},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78594ff15dcc4f05a412c2b04ab0d489",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":40,
                "y":356},
              "size":{
                "width":200,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ca10fb183454aefb8b8ddc0e31f3c61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":40,
                    "y":356},
                  "size":{
                    "width":200,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/领取广告_宽带业务/u10.png"}},
{
            "id":"4c20ee5a78e14909923e0d0fede69e51",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":99,
                "y":372},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3193db17fc8c4d3da903e5d2c5aee2fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":99,
                    "y":372},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "77709b3fdca844528934a4389a804b6a":{
      "packageId":"77709b3fdca844528934a4389a804b6a",
      "type":"Axure:Master",
      "name":"页头 已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"436c35237f7a4192a9de61ade8b072e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a8c4e1678bf419e89e028089ad41092",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"55e4cec996fa4bd98d77d44827b62a86",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce74cd922ea34d279d6d5bdc5f125d73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c65c9757d44d47a5b57c02491aa63dfc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":771,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"270ea7f3e5a7421aaf605bf2be76c814",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":771,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c857e624fe54b0ab532c11ad5bb5878",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":929,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93146bb689e494ea1e182df3b3964c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":929,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de94cc5f4864463881ef2d0cd4439c62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":850,
                "y":11},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13e05c5e0b7c47aa985e3e286a62cfa2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":850,
                    "y":11},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9cdd316832e441d4af9ee77d61b8d973",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":11},
              "size":{
                "width":88,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f33c1284a649aa8edf3eb51f242296",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":11},
                  "size":{
                    "width":88,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "89ab9973bd384ed88f7c755c5db53a11":{
      "scriptId":"u0"},
    "3fdfa22a9bef4e77b89da07fe19dd558":{
      "scriptId":"u1"},
    "3daf6f38e7bc48bc83ed4f5fa022e062":{
      "scriptId":"u2"},
    "22170b9662224fb99a464b6cb0c1db13":{
      "scriptId":"u3"},
    "b4fa64cb02034bbbab42088fec8459a4":{
      "scriptId":"u4"},
    "532270fd648a4e61a17009129ff92451":{
      "scriptId":"u5"},
    "e81ef5ae9fae4c0f896b172f89255972":{
      "scriptId":"u6"},
    "c37f51c42c3849ca9c4902dadf4dcd01":{
      "scriptId":"u7"},
    "5250c2edb1554df0bdc427b2b550ca3c":{
      "scriptId":"u8"},
    "2b64dc20a5d2482cabccb62d29aec6c9":{
      "scriptId":"u9"},
    "2c54562f64544ca7962d1c311006d9a4":{
      "scriptId":"u10"},
    "75ae685d516346f8b8e491d3e2d036ed":{
      "scriptId":"u11"},
    "72bcdcf7c046431981d8e02be20c6e79":{
      "scriptId":"u12"},
    "32c8660fd3a64fd3a32c53e35be360f3":{
      "scriptId":"u13"},
    "df17f19a7cd842c1924add873f58fabd":{
      "scriptId":"u14"},
    "6f88cf83d075402fa0d48e5a946c4ca0":{
      "scriptId":"u15"},
    "473209fb977d4157bf9b0fb1dce13445":{
      "scriptId":"u16"},
    "27263b5f53ee4c58932b47771211703d":{
      "scriptId":"u17"},
    "055d946f2978467ebfca0a787e2a9955":{
      "scriptId":"u18"},
    "e3b8b69c9dce4a90945f57d4e91d11ad":{
      "scriptId":"u19"},
    "81cec878703b4cd68ff79cffb4993f49":{
      "scriptId":"u20"},
    "ead1e6105ed742dfb3578aacefea2965":{
      "scriptId":"u21"},
    "35902a82bb2d49748a8967ae58a9afcf":{
      "scriptId":"u22"},
    "6ca9f086ddec420e95d0ed703699cc97":{
      "scriptId":"u23"},
    "6cbfe134c75b4d24b08dace08b2dad43":{
      "scriptId":"u24"},
    "d93968030a744fb98a60189983bf96d7":{
      "scriptId":"u25"},
    "3cd97e1ba07e4ea4966076cbdc37d798":{
      "scriptId":"u26"},
    "6600972b0a1648b28d8c69fe4162135c":{
      "scriptId":"u27"},
    "349704679fb74ee69c865b23be1ea86e":{
      "scriptId":"u28"},
    "05a92b51c0bb4dc89ad7998d1c9aa6dc":{
      "scriptId":"u29"},
    "b15600b96cbf428db66a3effd1c820fb":{
      "scriptId":"u30"},
    "ff9882d7d437451e9b9abe0dd3047dbe":{
      "scriptId":"u31"},
    "9e396db800f248479cdcf0ca2201cc06":{
      "scriptId":"u32"},
    "99f1eb559bf74b208a77a5dc1f0890d2":{
      "scriptId":"u33"},
    "5284f425aa694de0aaaaa5c784696d3c":{
      "scriptId":"u34"},
    "2f0fd2fd53bc4dc1841ba35d70bad7d6":{
      "scriptId":"u35"},
    "ea9e153f746244ca9f1d97ab8710aea5":{
      "scriptId":"u36"},
    "0bd5918886094651805d6b498bd8ec46":{
      "scriptId":"u37"},
    "658a8400409f4fb1ae5585420e17d33b":{
      "scriptId":"u38"},
    "19e8a7e1a2494ded9c4218ff2a3e96df":{
      "scriptId":"u39"},
    "da2af15b910c47ac9d72b70b125906c7":{
      "scriptId":"u40"},
    "dbba4069527c484998840ab038a98960":{
      "scriptId":"u41"},
    "91c5e33c319444f18414a11dcb1c58e3":{
      "scriptId":"u42"},
    "b5dfb47867904b569f0c72213185a819":{
      "scriptId":"u43"},
    "226694401e77422ca26ea2ccb7093a6a":{
      "scriptId":"u44"},
    "511e2ac0692041479d0a5308dfb98eb3":{
      "scriptId":"u45"},
    "5812c99171c74340bbc2540db11fafaf":{
      "scriptId":"u46"},
    "d92f4a384c084b968f101fad8fe44d17":{
      "scriptId":"u47"},
    "8041d18a887e425eb73734ce2c5dc681":{
      "scriptId":"u48"},
    "e6abd5d6b31a40e19ce7c0c2eaaba35f":{
      "scriptId":"u49"},
    "371499d5b7584d44a0ece8b24252df95":{
      "scriptId":"u50"},
    "5971543a9d394af6840ac58b2589e83c":{
      "scriptId":"u51"},
    "a099a57b84964a4f80ac5511078bbfe5":{
      "scriptId":"u52"},
    "d19ab83367de4fabb2926d6aa987f974":{
      "scriptId":"u53"},
    "eb7e48f746dd4cb19b0570a380e58505":{
      "scriptId":"u54"},
    "b10b75ed6e5a4101a04a79feb645084a":{
      "scriptId":"u55"},
    "f63b529953d145ab8649ef4960c9dc65":{
      "scriptId":"u56"},
    "984d48d8e12a405dabca027ef41da0f0":{
      "scriptId":"u57"},
    "4ae8ba2df3e24f3fa4ebf2568971a1eb":{
      "scriptId":"u58",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u59"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u60"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u61"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u62"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u63"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u64"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u65"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u66"}},
    "a793ea91988f401e96fa84e8a03132ca":{
      "scriptId":"u67",
      "56d85a7253f04f199871d3fdaac67eb6":{
        "scriptId":"u68"},
      "54d0d231dc57413eb216e8a5475c9dd0":{
        "scriptId":"u69"},
      "1e0f4221decc467292d7855ecad2942d":{
        "scriptId":"u70"},
      "bafca570fd364993af282bb72432579d":{
        "scriptId":"u71"},
      "bf065ea8e2524cb8a6fe5ddea7fa3ee7":{
        "scriptId":"u72"},
      "d9de695aac6647d9a7a33ed280804e6f":{
        "scriptId":"u73"},
      "d301701ccc33484cb2242ca2c53f2383":{
        "scriptId":"u74"},
      "b18f011200514edcbb595a928a0179d0":{
        "scriptId":"u75"},
      "4934ead7da71400c9ab43b14f6a362fa":{
        "scriptId":"u76"},
      "9be11e8fe52842128120aadc8b74603a":{
        "scriptId":"u77"},
      "07a775e9b30c46caa300e984c7cf67e2":{
        "scriptId":"u78"},
      "1b3dc8724bac4133ae5ee7395ca3ce67":{
        "scriptId":"u79"},
      "f5e3706d708b4504b18b68de0e7861c2":{
        "scriptId":"u80"},
      "2b79941f04eb4e0c9d70b99d96a1443b":{
        "scriptId":"u81"},
      "ac020511ea4c4647b1bf97d34c91b1e3":{
        "scriptId":"u82"},
      "15668114dd5d459f9801c82950ccd78d":{
        "scriptId":"u83"},
      "78594ff15dcc4f05a412c2b04ab0d489":{
        "scriptId":"u84"},
      "6ca10fb183454aefb8b8ddc0e31f3c61":{
        "scriptId":"u85"},
      "4c20ee5a78e14909923e0d0fede69e51":{
        "scriptId":"u86"},
      "3193db17fc8c4d3da903e5d2c5aee2fd":{
        "scriptId":"u87"}},
    "5fd0dc6e0e6941bcb43ae2d433d15540":{
      "scriptId":"u88"},
    "4774c4df22f746c9806db2ce2478b494":{
      "scriptId":"u89"},
    "4620e1df096f488ba5ebd47ec1f0fea4":{
      "scriptId":"u90"},
    "9792c3bbc8e9473bbe1c78104d45710c":{
      "scriptId":"u91"},
    "6dd3b9cdce994c9eb99c28714b32dac4":{
      "scriptId":"u92"},
    "e122554b087745e4baeaf34e2dff01a0":{
      "scriptId":"u93"},
    "683e48f9bf2f4cf2ab76f5c2ca4a25f5":{
      "scriptId":"u94",
      "436c35237f7a4192a9de61ade8b072e7":{
        "scriptId":"u95"},
      "0a8c4e1678bf419e89e028089ad41092":{
        "scriptId":"u96"},
      "55e4cec996fa4bd98d77d44827b62a86":{
        "scriptId":"u97"},
      "ce74cd922ea34d279d6d5bdc5f125d73":{
        "scriptId":"u98"},
      "c65c9757d44d47a5b57c02491aa63dfc":{
        "scriptId":"u99"},
      "270ea7f3e5a7421aaf605bf2be76c814":{
        "scriptId":"u100"},
      "8c857e624fe54b0ab532c11ad5bb5878":{
        "scriptId":"u101"},
      "c93146bb689e494ea1e182df3b3964c3":{
        "scriptId":"u102"},
      "de94cc5f4864463881ef2d0cd4439c62":{
        "scriptId":"u103"},
      "13e05c5e0b7c47aa985e3e286a62cfa2":{
        "scriptId":"u104"},
      "9cdd316832e441d4af9ee77d61b8d973":{
        "scriptId":"u105"},
      "67f33c1284a649aa8edf3eb51f242296":{
        "scriptId":"u106"}}}});