$axure.loadCurrentPage({
  "url":"注册_创建账号.html",
  "generationDate":new Date(1398670761612.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd845480650e4628964404bfdd9b0db5",
    "type":"Axure:Page",
    "name":"注册 创建账号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a5433eb8ee647c98efe067044f3919d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":36},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d488f0d74f345d298d4a3233fc01281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":36},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"54dc6f158794418080115a8605f75752",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":51},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ef8c4615d014802804a8cf4f7ca0ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":51},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"d169110033e840f9971f893bd654a39b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd2bda33c664b98ac81e027c7ad8952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87932a9ae6984b9583bcab61cdbdab19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":145},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7adc5942a94b470ba9ab63db612af280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":145},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"0b0f950a625c457c8b36dfb4886c6deb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":202},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9763c578103413bbb849001d3ac8f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":202},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"457258016fe9415987bea9764c4f0f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":193},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5083faf140444332b96b88fffdf81537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":193},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"518df35aabb547ae8cc1f615af8a385e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":209},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78ed80a74a00419b9d333e6edce07acc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":209},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f43f2bc23a642cf9c625d2c76719b6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":227,
              "y":821},
            "size":{
              "width":157,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04bb36a0b8bd406089318d69157ddfc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":227,
                  "y":821},
                "size":{
                  "width":157,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u14.png"}},
{
          "id":"26648471099340efb08485f81e711590",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":127,
              "y":114},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d2a73e0f8d14f27996358d3e36cdf34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":127,
                  "y":114},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"329d34c0869c4ba38ada4ad7746c67c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":250},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7151295d0294ac8b8d0000962b32bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":250},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81c34665b7b44c2182b8e6e8a40e3230",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":241},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b7cb3f91d6648b181fa22b74b30ed59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":241},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"c7bb600f6d184c2d94253b79da514caa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"856fa9c868c246398cd34220447c72af"},
{
          "id":"930b57bda8e144f682bdc46bb8f81821",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":142,
              "y":347},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0595dacce9e247a485a1696bc6de77db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":142,
                  "y":347},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42f0c9e01abb40338a551a5d66f34d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":338},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71a118375edc4f83911af5e4d2d78f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":338},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"9cae1f817a634334930786370b5f0ede",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":155,
              "y":391},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6738f9d4d4420fbe7a15248a5ac0a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":155,
                  "y":391},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27c448d5c80c48bea137d1a8525fd828",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":382},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c32842f2f734fccb869a99a648e7de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":382},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"f6fb0de7e9814bcf88a7e4b6540eb3c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":168,
              "y":437},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eed735ec3c34b508d3a964580d8a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":168,
                  "y":437},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c88b09582f495f8f04032642649946",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":428},
            "size":{
              "width":259,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af20fbabaa1947a8a540c89fbc10aa33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":428},
                "size":{
                  "width":259,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u6.png"}},
{
          "id":"64fdd090e25a45138c6beed6d8ff74f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":116,
              "y":295},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f301957874b44912a74f2f89b259e13e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":116,
                  "y":295},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a0b9560dc15440f80ec779793de2401",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":155,
              "y":786},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b52ee64a04e6411aac300727c618e64e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":155,
                  "y":786},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2eb42894b414d728b18c2a4ef9c1a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":227,
              "y":777},
            "size":{
              "width":139,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee473b9c4f64139baa4aa5b361944ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":777},
                "size":{
                  "width":139,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u47.png"}},
{
          "id":"2b6341cc7b284352b81f141b9e79e53e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":376,
              "y":777},
            "size":{
              "width":110,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f53c899a3de4b3fa2b90e02daabebc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":376,
                  "y":777},
                "size":{
                  "width":110,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u49.png"}},
{
          "id":"810343302fcd4fa1912afb58818dfa76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":168,
              "y":472},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4567ab6e30b42eaacc8b19ae76daa6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":168,
                  "y":472},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eede1dd252004b79b78ae4a9c8d5adf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":129,
              "y":574},
            "size":{
              "width":88,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673bb855e4a94a90ada9bfa6ab66d1b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":129,
                  "y":574},
                "size":{
                  "width":88,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eadde7ce1910427bbc97277e980cfe07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":376,
              "y":647},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e0dc7ff6887420aaa93cf8e8eb9ac13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":376,
                  "y":647},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caa279d26d694eeb8852c5bad44f1a23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":129,
              "y":677},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1510aa68273541bfba5c48773f5d0f5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":129,
                  "y":677},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2f5cbb1f8fc494483b3c35c28b0d13d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":574},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ba09a2bdbd4f67a24d2a0ca539ca18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":574},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}},
{
          "id":"2b80f7959a4c41448f2a99c75b019777",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":676},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce3d4b52bdf84546801b827c7db7e75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":676},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}},
{
          "id":"b9f566e1f8cf4c84827a66b697495692",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":376,
              "y":751},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0e1744277544408335b8ee9fe84e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":376,
                  "y":751},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dabdc6973589453f87c0449a4f7297ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":376,
              "y":545},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c00b42563514d279784c6acb779f838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":376,
                  "y":545},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01c73b77b7274e65b9025627ad6fc6f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":472},
            "size":{
              "width":139,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fd806c190da482a85db980b7bbfeda8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":472},
                "size":{
                  "width":139,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u59.png"}}]}},
  "masters":{
    "856fa9c868c246398cd34220447c72af":{
      "packageId":"856fa9c868c246398cd34220447c72af",
      "type":"Axure:Master",
      "name":"页头 未登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"856d0942702243c180a85de10078c777",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":1000,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12552d926b1449dcbc2feb2e26fecc25",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":1000,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u52.png"}},
{
            "id":"7765975770e74971b9f28e410420eb52",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":11},
              "size":{
                "width":92,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb177ed399a24ef4a2116442e4f55962",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":11},
                  "size":{
                    "width":92,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"484a0860066a4154b4cbed7134624825",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":872,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c395d628c06345f2950a5a8f7c0a5991",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":872,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5b7d53a9d1b94940925797b6c201ef1e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":810,
                "y":11},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b1e1ca4a0f72488faa27ced599f50796",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":810,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "3a5433eb8ee647c98efe067044f3919d":{
      "scriptId":"u0"},
    "5d488f0d74f345d298d4a3233fc01281":{
      "scriptId":"u1"},
    "54dc6f158794418080115a8605f75752":{
      "scriptId":"u2"},
    "7ef8c4615d014802804a8cf4f7ca0ada":{
      "scriptId":"u3"},
    "d169110033e840f9971f893bd654a39b":{
      "scriptId":"u4"},
    "2dd2bda33c664b98ac81e027c7ad8952":{
      "scriptId":"u5"},
    "87932a9ae6984b9583bcab61cdbdab19":{
      "scriptId":"u6"},
    "7adc5942a94b470ba9ab63db612af280":{
      "scriptId":"u7"},
    "0b0f950a625c457c8b36dfb4886c6deb":{
      "scriptId":"u8"},
    "f9763c578103413bbb849001d3ac8f3d":{
      "scriptId":"u9"},
    "457258016fe9415987bea9764c4f0f7f":{
      "scriptId":"u10"},
    "5083faf140444332b96b88fffdf81537":{
      "scriptId":"u11"},
    "518df35aabb547ae8cc1f615af8a385e":{
      "scriptId":"u12"},
    "78ed80a74a00419b9d333e6edce07acc":{
      "scriptId":"u13"},
    "1f43f2bc23a642cf9c625d2c76719b6a":{
      "scriptId":"u14"},
    "04bb36a0b8bd406089318d69157ddfc2":{
      "scriptId":"u15"},
    "26648471099340efb08485f81e711590":{
      "scriptId":"u16"},
    "8d2a73e0f8d14f27996358d3e36cdf34":{
      "scriptId":"u17"},
    "329d34c0869c4ba38ada4ad7746c67c6":{
      "scriptId":"u18"},
    "f7151295d0294ac8b8d0000962b32bb0":{
      "scriptId":"u19"},
    "81c34665b7b44c2182b8e6e8a40e3230":{
      "scriptId":"u20"},
    "8b7cb3f91d6648b181fa22b74b30ed59":{
      "scriptId":"u21"},
    "c7bb600f6d184c2d94253b79da514caa":{
      "scriptId":"u22",
      "856d0942702243c180a85de10078c777":{
        "scriptId":"u23"},
      "12552d926b1449dcbc2feb2e26fecc25":{
        "scriptId":"u24"},
      "7765975770e74971b9f28e410420eb52":{
        "scriptId":"u25"},
      "fb177ed399a24ef4a2116442e4f55962":{
        "scriptId":"u26"},
      "484a0860066a4154b4cbed7134624825":{
        "scriptId":"u27"},
      "c395d628c06345f2950a5a8f7c0a5991":{
        "scriptId":"u28"},
      "5b7d53a9d1b94940925797b6c201ef1e":{
        "scriptId":"u29"},
      "b1e1ca4a0f72488faa27ced599f50796":{
        "scriptId":"u30"}},
    "930b57bda8e144f682bdc46bb8f81821":{
      "scriptId":"u31"},
    "0595dacce9e247a485a1696bc6de77db":{
      "scriptId":"u32"},
    "42f0c9e01abb40338a551a5d66f34d62":{
      "scriptId":"u33"},
    "71a118375edc4f83911af5e4d2d78f1a":{
      "scriptId":"u34"},
    "9cae1f817a634334930786370b5f0ede":{
      "scriptId":"u35"},
    "5e6738f9d4d4420fbe7a15248a5ac0a1":{
      "scriptId":"u36"},
    "27c448d5c80c48bea137d1a8525fd828":{
      "scriptId":"u37"},
    "5c32842f2f734fccb869a99a648e7de6":{
      "scriptId":"u38"},
    "f6fb0de7e9814bcf88a7e4b6540eb3c9":{
      "scriptId":"u39"},
    "6eed735ec3c34b508d3a964580d8a22b":{
      "scriptId":"u40"},
    "d8c88b09582f495f8f04032642649946":{
      "scriptId":"u41"},
    "af20fbabaa1947a8a540c89fbc10aa33":{
      "scriptId":"u42"},
    "64fdd090e25a45138c6beed6d8ff74f3":{
      "scriptId":"u43"},
    "f301957874b44912a74f2f89b259e13e":{
      "scriptId":"u44"},
    "4a0b9560dc15440f80ec779793de2401":{
      "scriptId":"u45"},
    "b52ee64a04e6411aac300727c618e64e":{
      "scriptId":"u46"},
    "a2eb42894b414d728b18c2a4ef9c1a46":{
      "scriptId":"u47"},
    "0ee473b9c4f64139baa4aa5b361944ab":{
      "scriptId":"u48"},
    "2b6341cc7b284352b81f141b9e79e53e":{
      "scriptId":"u49"},
    "8f53c899a3de4b3fa2b90e02daabebc3":{
      "scriptId":"u50"},
    "810343302fcd4fa1912afb58818dfa76":{
      "scriptId":"u51"},
    "b4567ab6e30b42eaacc8b19ae76daa6b":{
      "scriptId":"u52"},
    "eede1dd252004b79b78ae4a9c8d5adf9":{
      "scriptId":"u53"},
    "673bb855e4a94a90ada9bfa6ab66d1b9":{
      "scriptId":"u54"},
    "eadde7ce1910427bbc97277e980cfe07":{
      "scriptId":"u55"},
    "6e0dc7ff6887420aaa93cf8e8eb9ac13":{
      "scriptId":"u56"},
    "caa279d26d694eeb8852c5bad44f1a23":{
      "scriptId":"u57"},
    "1510aa68273541bfba5c48773f5d0f5f":{
      "scriptId":"u58"},
    "b2f5cbb1f8fc494483b3c35c28b0d13d":{
      "scriptId":"u59"},
    "96ba09a2bdbd4f67a24d2a0ca539ca18":{
      "scriptId":"u60"},
    "2b80f7959a4c41448f2a99c75b019777":{
      "scriptId":"u61"},
    "ce3d4b52bdf84546801b827c7db7e75e":{
      "scriptId":"u62"},
    "b9f566e1f8cf4c84827a66b697495692":{
      "scriptId":"u63"},
    "7b0e1744277544408335b8ee9fe84e4c":{
      "scriptId":"u64"},
    "dabdc6973589453f87c0449a4f7297ca":{
      "scriptId":"u65"},
    "4c00b42563514d279784c6acb779f838":{
      "scriptId":"u66"},
    "01c73b77b7274e65b9025627ad6fc6f4":{
      "scriptId":"u67"},
    "5fd806c190da482a85db980b7bbfeda8":{
      "scriptId":"u68"}}});