$axure.loadCurrentPage({
  "url":"提示_未通过_需修改.html",
  "generationDate":new Date(1398670763421.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc2b8f8bbe124a0e9196894cf8c14574",
    "type":"Axure:Page",
    "name":"提示 未通过 需修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34b2f179fd9047ada81b0d93a9e84362",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9513d444285e4f3594035304d2693067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"678f6661528e4dc584944f7534c5bf12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":55},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1800ad4d435245c5a4ce38ca85a98091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":55},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"0100137cef874ac88f7edc264fc9b5cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":118},
            "size":{
              "width":870,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提示_审核中/u4_line.png"}},
{
          "id":"2e85df573ebf4b31832d2dcd6c9e1d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":184},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50edd9eb8d254b48a0ac49b5f8a12790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":184},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4645ef78034b4202b71f50d52deb4b9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":220},
            "size":{
              "width":465,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"292c28a975f74a969879593632a5774a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":220},
                "size":{
                  "width":465,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9635050fb61444d8ab0a933d60c7215f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":474,
              "y":249},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b6cc19e38b4ec08c140d4baa116a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":474,
                  "y":249},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "34b2f179fd9047ada81b0d93a9e84362":{
      "scriptId":"u0"},
    "9513d444285e4f3594035304d2693067":{
      "scriptId":"u1"},
    "678f6661528e4dc584944f7534c5bf12":{
      "scriptId":"u2"},
    "1800ad4d435245c5a4ce38ca85a98091":{
      "scriptId":"u3"},
    "0100137cef874ac88f7edc264fc9b5cf":{
      "scriptId":"u4"},
    "2e85df573ebf4b31832d2dcd6c9e1d12":{
      "scriptId":"u5"},
    "50edd9eb8d254b48a0ac49b5f8a12790":{
      "scriptId":"u6"},
    "4645ef78034b4202b71f50d52deb4b9d":{
      "scriptId":"u7"},
    "292c28a975f74a969879593632a5774a":{
      "scriptId":"u8"},
    "9635050fb61444d8ab0a933d60c7215f":{
      "scriptId":"u9"},
    "c0b6cc19e38b4ec08c140d4baa116a2b":{
      "scriptId":"u10"}}});