$axure.loadCurrentPage({
  "url":"提示_未通过_无资质.html",
  "generationDate":new Date(1398670763507.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c35422cce269418a97f5ef0531bca83c",
    "type":"Axure:Page",
    "name":"提示 未通过 无资质",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe5d425765214f4ebb0fbda56772beb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd48260cb0548678aedec1fff6498e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"269adf73fca2419d92e2bcbe2f3ca8c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":55},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc946f6f30e2458d892194af2536cfde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":55},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"375d34e45a06473e9a4fc635a6608696",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":118},
            "size":{
              "width":870,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提示_审核中/u4_line.png"}},
{
          "id":"06834724157e449da17a3d13edc435fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":189},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bcfa9de29fc4bda8a70f9a84216a6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":189},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48089ef457834c19a88f73ef8fc2d181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":258,
              "y":215},
            "size":{
              "width":456,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ef290252a54ffc904d95cf4e296e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":258,
                  "y":215},
                "size":{
                  "width":456,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30d8277f65df44ee97567f5ff9f7c770",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":459,
              "y":274},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef36c5e252448a4aac8680c4c190768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":274},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fe5d425765214f4ebb0fbda56772beb6":{
      "scriptId":"u0"},
    "ecd48260cb0548678aedec1fff6498e9":{
      "scriptId":"u1"},
    "269adf73fca2419d92e2bcbe2f3ca8c4":{
      "scriptId":"u2"},
    "cc946f6f30e2458d892194af2536cfde":{
      "scriptId":"u3"},
    "375d34e45a06473e9a4fc635a6608696":{
      "scriptId":"u4"},
    "06834724157e449da17a3d13edc435fa":{
      "scriptId":"u5"},
    "6bcfa9de29fc4bda8a70f9a84216a6ef":{
      "scriptId":"u6"},
    "48089ef457834c19a88f73ef8fc2d181":{
      "scriptId":"u7"},
    "b8ef290252a54ffc904d95cf4e296e01":{
      "scriptId":"u8"},
    "30d8277f65df44ee97567f5ff9f7c770":{
      "scriptId":"u9"},
    "8ef36c5e252448a4aac8680c4c190768":{
      "scriptId":"u10"}}});