$axure.loadCurrentPage({
  "url":"领取广告_宽带业务.html",
  "generationDate":new Date(1398670764106.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"218c656e3e4c47758116d6482eb60bc6",
    "type":"Axure:Page",
    "name":"领取广告 宽带业务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"453b62d6a501454cb9b8bf090b8c230b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c2718f5bd943be8f5b6eee05c7cf4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"2404d32a53204f03bd10a8f7f820a4ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":47},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c622c70a0a4249fcae7a4b6e53492582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":47},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"d46b7b085e36420ba878a56d044c88dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":160},
            "size":{
              "width":750,
              "height":980},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347fc24e84664101b8606857ce39c02c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":160},
                "size":{
                  "width":750,
                  "height":980},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u4.png"}},
{
          "id":"b8de39a8460c40f191d5fcef9eecc86d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46a80574575426ea1d377f64c4bff7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u6.png"}},
{
          "id":"36c51bd9cea045d2b89c3dc4fdada36c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":99,
              "y":176},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d102b4481cd94e12b54f9ec37f7b5964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":99,
                  "y":176},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"780a1019eb29462589e8a8baa78e9c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":209},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3302e30ec2742a0aee4a4c9c0f48776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":209},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u10.png"}},
{
          "id":"32516a2828a04ed8b65fcac9b644772d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":99,
              "y":224},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd5be53a6bbe4e0b9317d7001fa6d0c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":99,
                  "y":224},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"543e1c6ead0a4033b02b802c78abcb10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":258},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ead84a3924343a48eda873cb4c37cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":258},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u10.png"}},
{
          "id":"9f64b4a4ffb44eff99c0ef5bad61bbe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":91,
              "y":274},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260f4a52dff54807baaad27d9920e055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":91,
                  "y":274},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"321ca5866637496aa8acfafdb9d962c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":307},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2117b7e58684c91886ffde9ec0c747c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":307},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u10.png"}},
{
          "id":"cf20a32ce8d6425ba71d597e1af68de1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":115,
              "y":322},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec19351e8cf45bc965119d2ae82998d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":115,
                  "y":322},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f78b4691600a418ba9cbff27afe5a52b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":205,
              "y":175},
            "size":{
              "width":17,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9cc4f3a0c024f78a43f371f0fe23742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":205,
                  "y":175},
                "size":{
                  "width":17,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u22.png"}},
{
          "id":"da3b129f4fea43f6a4992c1ca9730849",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":209},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b6bd9ccada4ec2b20050b6bd390056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":209},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d83f4cb0a7d4c70a1e3ace5719162b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":374,
              "y":209},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4c89f40712467abd127f61ddd9bfc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":374,
                  "y":209},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b88d5e546b124373b48d66f3a0349934",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":236},
            "size":{
              "width":617,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca5888ac00b24eb999853d96ca751ad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":236},
                "size":{
                  "width":617,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1ad7cf938de409a894d898afe878b99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":263},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3421ec2abf34443d8878b3e6eb347652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":263},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51a335800a354ba6a2cfcc2da2f60a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":303,
              "y":289},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2f34697adc4c8d9a132e1558263104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":303,
                  "y":289},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1737bbbf9eb435480aae0303bc41cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":320},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c5af30442941a0b481b73a23d958a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":320},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"059a92d8b8b643dcb7bb12896c95b735",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":182},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c24c87bfa7504a01909a015cad10ceed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":182},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bacf4538e95d43f189f52816e7e289ac",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":351},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c6b2ca4d4664e1d8be56531afbce8dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":351},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ab2b0ea6db904f41931527aca577a119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":375},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf1dbc91cd840f999092cc07e66b74b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":375},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda450e02bd14cd298bca4e82b23d41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":430},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df4beac93af84843962a2c02c9d61031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":430},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff64b606a71f4e4b9b3a83288c5b0f84",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":430},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04884099c4374deba5368566edad0d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":430},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"86fcd1a00b5e4c4abc382d9d490c4c8d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":430},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c93cbed1d7234413878688a86b7b6410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":430},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"36f12e169bba4ab48bb636b14a893001",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":459},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0499651ed9c2422fba8e4c7fd2b6536b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":459},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8934fa87a1f47bb8f984aff00e636b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":455},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea2cf28c2494926ac732f8a900298d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":455},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"825f8c5d182640cfad52392fd73ab3cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":455},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98c8e5807a62471891b9ea288c6077ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":455},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"e230aa40980b4876937dc6a0611dac7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":558,
              "y":459},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e81e2f50a5df4cf0a257cf9009a3f910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":558,
                  "y":459},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"351661b80bf3405e8d363bb647d0e9fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":639,
              "y":455},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb33f9fc394d41eb82e9661e4a5a4936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":639,
                  "y":455},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u50.png"}},
{
          "id":"7a47e9dad0ef4c9793ed0108bee0f78b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":667,
              "y":455},
            "size":{
              "width":83,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6868b81637d40e1afbc19a16e120508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":667,
                  "y":455},
                "size":{
                  "width":83,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u52.png"}},
{
          "id":"fa089186a5a64a2ea64c3818b13fc66a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":489},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5215f426d2fd4ad987ad2d46c49006cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":489},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c26b0704b6fd44ab86133d70c0e76fa4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":516},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57e87b3e6b14e4c8ddd7113d5ad6ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":516},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"032573eb2677402fa2aafabdd4f799b9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":516},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5242e494994d8481cee120d59bea0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":516},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"17238d50504d426b99f4acebf807ed27",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":516},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f74a990e0194cc58e09e06929c5bd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":516},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"08f59cdd95fb431aa7caacd351d1ca80",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":516},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e89c37cb1f5148bb8bfdab0dd1b9e167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":654,
                  "y":516},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7676c71dadf44a53a3fd966d34e36f35",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":541},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5664bf1167b54cad9dd7aedf328f64cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":541},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f62c08657cb24be086536a64ae0e0480",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":541},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dd12206d7dc42b4a0de5cf98a653450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":541},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5609b6e9f101401481fcc86335ce3fe1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":541},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda8ccb1aa8e4200ae748f1f2a51bd6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":541},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ea780052a0ea4c31a504545456c78a2b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":541},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"594667747b644a2d9200d32b6a9e33c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":654,
                  "y":541},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"26dad965ac044b39bda63c525d407320",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":567},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1fdc49b9d5947a48b911080a0bfb53a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":567},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"24bf6f25e5b941438c967ebc25006545",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":567},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f81434e01da404292f026825af9f901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":567},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ff7b6d11576143d3ab9db070377dcab2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":567},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7478e0c91afb4954a1e90452444aa944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":567},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"52e06fc49b054470ac21a8e67ab6e8b0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":567},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122ff85b3fd54332860f64fc1ae9dba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":654,
                  "y":567},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9c226062423746d08ab6aebee36d9b8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":593},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f68cf920254ff5879c80b83f05a45e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":593},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f955b6f8c9241bca4d900b5a4859ece",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":620},
            "size":{
              "width":200,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"825798efe0c1433fbb0eb61a3259b2a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":620},
                "size":{
                  "width":200,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u88.png"}},
{
          "id":"f1bdc69368a94811b8b6bbc3cc205e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":520,
              "y":780},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52b9ae8eeaf4db88a0dfb3008521b3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":520,
                  "y":780},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94dda305bb3b4eeb9db51b668bb05416",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":283,
              "y":810},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42ff2615c514c22b851ff660bfcc7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":283,
                  "y":810},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bfc412f33754c35abeec87effef65b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":862},
            "size":{
              "width":590,
              "height":128},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089ab02e959a47828dc85cfa74731ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":862},
                "size":{
                  "width":590,
                  "height":128},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u94.png"}},
{
          "id":"3256fc0e92424d939da9dd9edf092524",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":836},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d83d0a58b42148ef8e7655d9c82c6920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":836},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c143ef1eea2243fa9e58f05587d7672d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":529,
              "y":1000},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f36f901463440a886a2cd15df2236e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":529,
                  "y":1000},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"a28664328e9f4cbfbae0f4e8e8827845",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":1054},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b82bc5bfa324089b16f3e87b561882d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":1054},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e97c515907a941df8004e386197165a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":1080},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591e0a41bd004cbb928698d29f8a41fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":1080},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u102.png"}},
{
          "id":"8ab3769cd580436e98c6c3ff265fcceb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1F94D6},
            "location":{
              "x":620,
              "y":1080},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cfc979acd8a427eb05adafd084e10ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1F94D6},
                "location":{
                  "x":620,
                  "y":1080},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取广告_宽带业务/u98.png"}},
{
          "id":"387d7170c4c9478392de9311c9b4e826",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":133},
            "size":{
              "width":129,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f6e8a89914646f39c9ff6c2fb562aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":133},
                "size":{
                  "width":129,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"398e4c633a97425388a7f385a901647b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":403},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e69dd944fa04ef0860e5b4f78fe4004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":403},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c81c0c11fe415daa2b5bf082978c7c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":403},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c225cf1ab04d484e86fdecae6fd2fb34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":403},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1886ba5f0ff34a9f905529f78174aba2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":403},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3735cb3d413b4be6ab7f4b0d96edbb4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":403},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c56c5aa7c1e140d4b6269606da2a1fa3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":601,
              "y":403},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc8c6fa50d94b4fbf04731bd63202ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":601,
                  "y":403},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"37e3065ed29743b28920e816949aedff",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":80}},
          "adaptiveStyles":{
},
          "masterId":"2a63c66e4c224c64837abc6694aca48a"}]}},
  "masters":{
    "2a63c66e4c224c64837abc6694aca48a":{
      "packageId":"2a63c66e4c224c64837abc6694aca48a",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1578f5efeed24c18bba0b35d0b9bddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b09117a48b934130beaa150b9d2dbcb9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"edead5edf77c47049a4715b0018e30a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":419,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ddc2ded08a94063883ec821c50474c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":419,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"806ff3f46acb4738b6fe5a20fd661466",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":514,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c08c14c3c7cf4a2a874e6896955cf2b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":514,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}},
{
            "id":"9ef5ede7129c43a8a96d32687673448d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":324,
                "y":96},
              "size":{
                "width":96,
                "height":34},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"613412468d5e4c2985b8e3187eff8c08",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":324,
                    "y":96},
                  "size":{
                    "width":96,
                    "height":34},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/前端_首页/u43.png"}}]}}},
  "objectPaths":{
    "453b62d6a501454cb9b8bf090b8c230b":{
      "scriptId":"u0"},
    "d4c2718f5bd943be8f5b6eee05c7cf4d":{
      "scriptId":"u1"},
    "2404d32a53204f03bd10a8f7f820a4ea":{
      "scriptId":"u2"},
    "c622c70a0a4249fcae7a4b6e53492582":{
      "scriptId":"u3"},
    "d46b7b085e36420ba878a56d044c88dc":{
      "scriptId":"u4"},
    "347fc24e84664101b8606857ce39c02c":{
      "scriptId":"u5"},
    "b8de39a8460c40f191d5fcef9eecc86d":{
      "scriptId":"u6"},
    "b46a80574575426ea1d377f64c4bff7f":{
      "scriptId":"u7"},
    "36c51bd9cea045d2b89c3dc4fdada36c":{
      "scriptId":"u8"},
    "d102b4481cd94e12b54f9ec37f7b5964":{
      "scriptId":"u9"},
    "780a1019eb29462589e8a8baa78e9c20":{
      "scriptId":"u10"},
    "a3302e30ec2742a0aee4a4c9c0f48776":{
      "scriptId":"u11"},
    "32516a2828a04ed8b65fcac9b644772d":{
      "scriptId":"u12"},
    "dd5be53a6bbe4e0b9317d7001fa6d0c8":{
      "scriptId":"u13"},
    "543e1c6ead0a4033b02b802c78abcb10":{
      "scriptId":"u14"},
    "3ead84a3924343a48eda873cb4c37cc8":{
      "scriptId":"u15"},
    "9f64b4a4ffb44eff99c0ef5bad61bbe1":{
      "scriptId":"u16"},
    "260f4a52dff54807baaad27d9920e055":{
      "scriptId":"u17"},
    "321ca5866637496aa8acfafdb9d962c8":{
      "scriptId":"u18"},
    "e2117b7e58684c91886ffde9ec0c747c":{
      "scriptId":"u19"},
    "cf20a32ce8d6425ba71d597e1af68de1":{
      "scriptId":"u20"},
    "6ec19351e8cf45bc965119d2ae82998d":{
      "scriptId":"u21"},
    "f78b4691600a418ba9cbff27afe5a52b":{
      "scriptId":"u22"},
    "b9cc4f3a0c024f78a43f371f0fe23742":{
      "scriptId":"u23"},
    "da3b129f4fea43f6a4992c1ca9730849":{
      "scriptId":"u24"},
    "93b6bd9ccada4ec2b20050b6bd390056":{
      "scriptId":"u25"},
    "8d83f4cb0a7d4c70a1e3ace5719162b3":{
      "scriptId":"u26"},
    "4e4c89f40712467abd127f61ddd9bfc3":{
      "scriptId":"u27"},
    "b88d5e546b124373b48d66f3a0349934":{
      "scriptId":"u28"},
    "ca5888ac00b24eb999853d96ca751ad4":{
      "scriptId":"u29"},
    "f1ad7cf938de409a894d898afe878b99":{
      "scriptId":"u30"},
    "3421ec2abf34443d8878b3e6eb347652":{
      "scriptId":"u31"},
    "51a335800a354ba6a2cfcc2da2f60a71":{
      "scriptId":"u32"},
    "6d2f34697adc4c8d9a132e1558263104":{
      "scriptId":"u33"},
    "c1737bbbf9eb435480aae0303bc41cea":{
      "scriptId":"u34"},
    "85c5af30442941a0b481b73a23d958a3":{
      "scriptId":"u35"},
    "059a92d8b8b643dcb7bb12896c95b735":{
      "scriptId":"u36"},
    "c24c87bfa7504a01909a015cad10ceed":{
      "scriptId":"u37"},
    "bacf4538e95d43f189f52816e7e289ac":{
      "scriptId":"u38"},
    "1c6b2ca4d4664e1d8be56531afbce8dd":{
      "scriptId":"u39"},
    "ab2b0ea6db904f41931527aca577a119":{
      "scriptId":"u40"},
    "cbf1dbc91cd840f999092cc07e66b74b":{
      "scriptId":"u41"},
    "fda450e02bd14cd298bca4e82b23d41d":{
      "scriptId":"u42"},
    "df4beac93af84843962a2c02c9d61031":{
      "scriptId":"u43"},
    "ff64b606a71f4e4b9b3a83288c5b0f84":{
      "scriptId":"u44"},
    "04884099c4374deba5368566edad0d8c":{
      "scriptId":"u45"},
    "86fcd1a00b5e4c4abc382d9d490c4c8d":{
      "scriptId":"u46"},
    "c93cbed1d7234413878688a86b7b6410":{
      "scriptId":"u47"},
    "36f12e169bba4ab48bb636b14a893001":{
      "scriptId":"u48"},
    "0499651ed9c2422fba8e4c7fd2b6536b":{
      "scriptId":"u49"},
    "d8934fa87a1f47bb8f984aff00e636b7":{
      "scriptId":"u50"},
    "9ea2cf28c2494926ac732f8a900298d1":{
      "scriptId":"u51"},
    "825f8c5d182640cfad52392fd73ab3cc":{
      "scriptId":"u52"},
    "98c8e5807a62471891b9ea288c6077ee":{
      "scriptId":"u53"},
    "e230aa40980b4876937dc6a0611dac7f":{
      "scriptId":"u54"},
    "e81e2f50a5df4cf0a257cf9009a3f910":{
      "scriptId":"u55"},
    "351661b80bf3405e8d363bb647d0e9fd":{
      "scriptId":"u56"},
    "eb33f9fc394d41eb82e9661e4a5a4936":{
      "scriptId":"u57"},
    "7a47e9dad0ef4c9793ed0108bee0f78b":{
      "scriptId":"u58"},
    "b6868b81637d40e1afbc19a16e120508":{
      "scriptId":"u59"},
    "fa089186a5a64a2ea64c3818b13fc66a":{
      "scriptId":"u60"},
    "5215f426d2fd4ad987ad2d46c49006cf":{
      "scriptId":"u61"},
    "c26b0704b6fd44ab86133d70c0e76fa4":{
      "scriptId":"u62"},
    "c57e87b3e6b14e4c8ddd7113d5ad6ed3":{
      "scriptId":"u63"},
    "032573eb2677402fa2aafabdd4f799b9":{
      "scriptId":"u64"},
    "8f5242e494994d8481cee120d59bea0f":{
      "scriptId":"u65"},
    "17238d50504d426b99f4acebf807ed27":{
      "scriptId":"u66"},
    "3f74a990e0194cc58e09e06929c5bd94":{
      "scriptId":"u67"},
    "08f59cdd95fb431aa7caacd351d1ca80":{
      "scriptId":"u68"},
    "e89c37cb1f5148bb8bfdab0dd1b9e167":{
      "scriptId":"u69"},
    "7676c71dadf44a53a3fd966d34e36f35":{
      "scriptId":"u70"},
    "5664bf1167b54cad9dd7aedf328f64cb":{
      "scriptId":"u71"},
    "f62c08657cb24be086536a64ae0e0480":{
      "scriptId":"u72"},
    "4dd12206d7dc42b4a0de5cf98a653450":{
      "scriptId":"u73"},
    "5609b6e9f101401481fcc86335ce3fe1":{
      "scriptId":"u74"},
    "eda8ccb1aa8e4200ae748f1f2a51bd6d":{
      "scriptId":"u75"},
    "ea780052a0ea4c31a504545456c78a2b":{
      "scriptId":"u76"},
    "594667747b644a2d9200d32b6a9e33c9":{
      "scriptId":"u77"},
    "26dad965ac044b39bda63c525d407320":{
      "scriptId":"u78"},
    "e1fdc49b9d5947a48b911080a0bfb53a":{
      "scriptId":"u79"},
    "24bf6f25e5b941438c967ebc25006545":{
      "scriptId":"u80"},
    "9f81434e01da404292f026825af9f901":{
      "scriptId":"u81"},
    "ff7b6d11576143d3ab9db070377dcab2":{
      "scriptId":"u82"},
    "7478e0c91afb4954a1e90452444aa944":{
      "scriptId":"u83"},
    "52e06fc49b054470ac21a8e67ab6e8b0":{
      "scriptId":"u84"},
    "122ff85b3fd54332860f64fc1ae9dba9":{
      "scriptId":"u85"},
    "9c226062423746d08ab6aebee36d9b8c":{
      "scriptId":"u86"},
    "94f68cf920254ff5879c80b83f05a45e":{
      "scriptId":"u87"},
    "7f955b6f8c9241bca4d900b5a4859ece":{
      "scriptId":"u88"},
    "825798efe0c1433fbb0eb61a3259b2a2":{
      "scriptId":"u89"},
    "f1bdc69368a94811b8b6bbc3cc205e16":{
      "scriptId":"u90"},
    "f52b9ae8eeaf4db88a0dfb3008521b3b":{
      "scriptId":"u91"},
    "94dda305bb3b4eeb9db51b668bb05416":{
      "scriptId":"u92"},
    "d42ff2615c514c22b851ff660bfcc7bd":{
      "scriptId":"u93"},
    "6bfc412f33754c35abeec87effef65b9":{
      "scriptId":"u94"},
    "089ab02e959a47828dc85cfa74731ef6":{
      "scriptId":"u95"},
    "3256fc0e92424d939da9dd9edf092524":{
      "scriptId":"u96"},
    "d83d0a58b42148ef8e7655d9c82c6920":{
      "scriptId":"u97"},
    "c143ef1eea2243fa9e58f05587d7672d":{
      "scriptId":"u98"},
    "07f36f901463440a886a2cd15df2236e":{
      "scriptId":"u99"},
    "a28664328e9f4cbfbae0f4e8e8827845":{
      "scriptId":"u100"},
    "1b82bc5bfa324089b16f3e87b561882d":{
      "scriptId":"u101"},
    "e97c515907a941df8004e386197165a0":{
      "scriptId":"u102"},
    "591e0a41bd004cbb928698d29f8a41fc":{
      "scriptId":"u103"},
    "8ab3769cd580436e98c6c3ff265fcceb":{
      "scriptId":"u104"},
    "8cfc979acd8a427eb05adafd084e10ef":{
      "scriptId":"u105"},
    "387d7170c4c9478392de9311c9b4e826":{
      "scriptId":"u106"},
    "4f6e8a89914646f39c9ff6c2fb562aa7":{
      "scriptId":"u107"},
    "398e4c633a97425388a7f385a901647b":{
      "scriptId":"u108"},
    "2e69dd944fa04ef0860e5b4f78fe4004":{
      "scriptId":"u109"},
    "95c81c0c11fe415daa2b5bf082978c7c":{
      "scriptId":"u110"},
    "c225cf1ab04d484e86fdecae6fd2fb34":{
      "scriptId":"u111"},
    "1886ba5f0ff34a9f905529f78174aba2":{
      "scriptId":"u112"},
    "3735cb3d413b4be6ab7f4b0d96edbb4c":{
      "scriptId":"u113"},
    "c56c5aa7c1e140d4b6269606da2a1fa3":{
      "scriptId":"u114"},
    "1fc8c6fa50d94b4fbf04731bd63202ef":{
      "scriptId":"u115"},
    "37e3065ed29743b28920e816949aedff":{
      "scriptId":"u116",
      "1578f5efeed24c18bba0b35d0b9bddec":{
        "scriptId":"u117"},
      "b09117a48b934130beaa150b9d2dbcb9":{
        "scriptId":"u118"},
      "edead5edf77c47049a4715b0018e30a6":{
        "scriptId":"u119"},
      "6ddc2ded08a94063883ec821c50474c7":{
        "scriptId":"u120"},
      "806ff3f46acb4738b6fe5a20fd661466":{
        "scriptId":"u121"},
      "c08c14c3c7cf4a2a874e6896955cf2b7":{
        "scriptId":"u122"},
      "9ef5ede7129c43a8a96d32687673448d":{
        "scriptId":"u123"},
      "613412468d5e4c2985b8e3187eff8c08":{
        "scriptId":"u124"}}}});