$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1398670763224.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"62dc43e9e9ec413992a51c692520b108",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ecf057cf98a447db938cab862c1b1f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":192,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a8ffc353694ae98381f79ae2515159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":192,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u0.png"}},
{
          "id":"81bedcbe19244d4c9a2872df2a87a643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":55},
            "size":{
              "width":120,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37e0aa149c2648e2b79d8372c1e9116b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":55},
                "size":{
                  "width":120,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/前端_首页/u2.png"}},
{
          "id":"4ccdd21fdf1347b3b923d71e6e119b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":140},
            "size":{
              "width":390,
              "height":270},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b959de103fce4377b920cdd19a213334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":140},
                "size":{
                  "width":390,
                  "height":270},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"cbc53a3b3b084f84af1f8739bdb5836f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":165},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c04cfdde794cbca4e9e0a084365d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":165},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ca6751c822a4d25afe07ab231a2368d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":530,
              "y":156},
            "size":{
              "width":220,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ba08885806429db460a2c25baf7d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":156},
                "size":{
                  "width":220,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u8.png"}},
{
          "id":"e2384e7b2be44b60b9a77d474e5782c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":224},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"626a9973a82048838b0db58c295a59a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":224},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c4b9e3254fa481291157eea49456a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":530,
              "y":215},
            "size":{
              "width":220,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c3cda7851249b784cb8f83555ae97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":215},
                "size":{
                  "width":220,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u8.png"}},
{
          "id":"97464ea321ed4c9fa6a5652624c4f2a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":479,
              "y":298},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1c785043b1c46ffa5474fb601f335dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":479,
                  "y":298},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b760e91f2684d7db47482b578f68c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":529,
              "y":289},
            "size":{
              "width":100,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"153ea636bfd64ce6a30fa07b3de737c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":529,
                  "y":289},
                "size":{
                  "width":100,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u16.png"}},
{
          "id":"664681ca992a42168b1bad2a311af353",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":639,
              "y":282},
            "size":{
              "width":162,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ce43ef542a410c9368fc2efa388a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":639,
                  "y":282},
                "size":{
                  "width":162,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u18.png"}},
{
          "id":"4c8aa9bb5cbb459d991c556bd0ce6758",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":530,
              "y":255},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f43e8f3d964983b953dd5074d686be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":255},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13aded857fbf43ce824a033d8f8661f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":697,
              "y":388},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105a92826df44ab48f1a631c0cc6145a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":697,
                  "y":388},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd07532af3984f92806c118d88409042",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":530,
              "y":366},
            "size":{
              "width":157,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d455530759b945fd856877e721100c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":530,
                  "y":366},
                "size":{
                  "width":157,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册_创建账号/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6ecf057cf98a447db938cab862c1b1f4":{
      "scriptId":"u0"},
    "84a8ffc353694ae98381f79ae2515159":{
      "scriptId":"u1"},
    "81bedcbe19244d4c9a2872df2a87a643":{
      "scriptId":"u2"},
    "37e0aa149c2648e2b79d8372c1e9116b":{
      "scriptId":"u3"},
    "4ccdd21fdf1347b3b923d71e6e119b7b":{
      "scriptId":"u4"},
    "b959de103fce4377b920cdd19a213334":{
      "scriptId":"u5"},
    "cbc53a3b3b084f84af1f8739bdb5836f":{
      "scriptId":"u6"},
    "a0c04cfdde794cbca4e9e0a084365d17":{
      "scriptId":"u7"},
    "6ca6751c822a4d25afe07ab231a2368d":{
      "scriptId":"u8"},
    "44ba08885806429db460a2c25baf7d75":{
      "scriptId":"u9"},
    "e2384e7b2be44b60b9a77d474e5782c1":{
      "scriptId":"u10"},
    "626a9973a82048838b0db58c295a59a5":{
      "scriptId":"u11"},
    "7c4b9e3254fa481291157eea49456a3c":{
      "scriptId":"u12"},
    "24c3cda7851249b784cb8f83555ae97d":{
      "scriptId":"u13"},
    "97464ea321ed4c9fa6a5652624c4f2a7":{
      "scriptId":"u14"},
    "f1c785043b1c46ffa5474fb601f335dd":{
      "scriptId":"u15"},
    "4b760e91f2684d7db47482b578f68c45":{
      "scriptId":"u16"},
    "153ea636bfd64ce6a30fa07b3de737c0":{
      "scriptId":"u17"},
    "664681ca992a42168b1bad2a311af353":{
      "scriptId":"u18"},
    "10ce43ef542a410c9368fc2efa388a00":{
      "scriptId":"u19"},
    "4c8aa9bb5cbb459d991c556bd0ce6758":{
      "scriptId":"u20"},
    "75f43e8f3d964983b953dd5074d686be":{
      "scriptId":"u21"},
    "13aded857fbf43ce824a033d8f8661f8":{
      "scriptId":"u22"},
    "105a92826df44ab48f1a631c0cc6145a":{
      "scriptId":"u23"},
    "fd07532af3984f92806c118d88409042":{
      "scriptId":"u24"},
    "d455530759b945fd856877e721100c4a":{
      "scriptId":"u25"}}});